# Generated by Django 5.2.16 on 2026-07-13 22:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0003_charactergroup_characterrelationship_groupmembership_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("order", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("hiatus", "Hiatus"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volumes",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Arc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("order", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("hiatus", "Hiatus"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arcs",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arcs",
                        to="stories.volume",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("web_serial", "Web serial"),
                            ("novel", "Novel"),
                            ("novella", "Novella"),
                            ("short_story", "Short story"),
                            ("screenplay", "Screenplay"),
                            ("stage_play", "Stage play"),
                            ("comic", "Comic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("planning", "Planning"),
                            ("drafting", "Drafting"),
                            ("revising", "Revising"),
                            ("complete", "Complete"),
                            ("hiatus", "Hiatus"),
                            ("archived", "Archived"),
                        ],
                        default="idea",
                        max_length=16,
                    ),
                ),
                ("premise", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("intended_audience", models.CharField(blank=True, max_length=240)),
                ("genre_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="volume",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volumes",
                to="stories.work",
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brainstorm", "Brainstorm"),
                            ("outlining", "Outlining"),
                            ("drafting", "Drafting"),
                            ("revising", "Revising"),
                            ("polished", "Polished"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="brainstorm",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to="stories.arc",
                    ),
                ),
                (
                    "pov_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pov_chapters",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to="stories.volume",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to="stories.work",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="arc",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="arcs", to="stories.work"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["workspace", "-updated_at"], name="work_ws_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["workspace", "status"], name="work_ws_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")), name="work_title_contains_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "work_type__in",
                        (
                            "web_serial",
                            "novel",
                            "novella",
                            "short_story",
                            "screenplay",
                            "stage_play",
                            "comic",
                            "other",
                        ),
                    )
                ),
                name="work_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "idea",
                            "planning",
                            "drafting",
                            "revising",
                            "complete",
                            "hiatus",
                            "archived",
                        ),
                    )
                ),
                name="work_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(
                fields=["workspace", "work", "order"], name="volume_ws_work_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")), name="volume_title_contains_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("planned", "active", "complete", "hiatus", "archived"))
                ),
                name="volume_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("work", "order"), name="unique_volume_order_in_work"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["workspace", "work", "order"], name="chapter_ws_work_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")), name="chapter_title_contains_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "brainstorm",
                            "outlining",
                            "drafting",
                            "revising",
                            "polished",
                            "published",
                            "archived",
                        ),
                    )
                ),
                name="chapter_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("work", "order"), name="unique_chapter_order_in_work"
            ),
        ),
        migrations.AddIndex(
            model_name="arc",
            index=models.Index(fields=["workspace", "work", "order"], name="arc_ws_work_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="arc",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")), name="arc_title_contains_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="arc",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("planned", "active", "complete", "hiatus", "archived"))
                ),
                name="arc_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="arc",
            constraint=models.UniqueConstraint(
                fields=("work", "order"), name="unique_arc_order_in_work"
            ),
        ),
    ]
