# Generated by Django 5.2.16 on 2026-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="brain_dump",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="character_focus",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="concept",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="emotional_arc",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="key_beats",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="outline",
            field=models.TextField(blank=True),
        ),
    ]
