# Generated by Django 5.2.16 on 2026-07-18 00:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("timeline", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="editorial_concerns",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="final_check_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="revision_priorities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="unresolved_questions",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ChapterPlanningSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=240)),
                ("trigger", models.CharField(default="manual", max_length=32)),
                ("planning_content", models.JSONField(default=dict)),
                ("beat_data", models.JSONField(default=list)),
                ("pacing_data", models.JSONField(default=dict)),
                ("source_ai_request_id", models.UUIDField(blank=True, null=True)),
                ("source_ai_suggestion_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_snapshots",
                        to="stories.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="WritingDelta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("activity_date", models.DateField()),
                ("word_delta", models.PositiveIntegerField(default=0)),
                ("resulting_word_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writing_deltas",
                        to="stories.chapter",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writing_delta",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writing_deltas",
                        to="scenes.scene",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writing_deltas",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writing_deltas",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-activity_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ChapterBeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=240)),
                (
                    "beat_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening"),
                            ("setup", "Setup"),
                            ("escalation", "Escalation"),
                            ("discovery", "Discovery"),
                            ("confrontation", "Confrontation"),
                            ("reversal", "Reversal"),
                            ("decision", "Decision"),
                            ("revelation", "Revelation"),
                            ("emotional_turn", "Emotional turn"),
                            ("action", "Action"),
                            ("transition", "Transition"),
                            ("climax", "Climax"),
                            ("aftermath", "Aftermath"),
                            ("hook", "Hook"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("emotional_direction", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("drafted", "Drafted"),
                            ("represented", "Represented in Scene"),
                            ("revised", "Revised"),
                            ("cut", "Cut"),
                        ],
                        default="planned",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_beats",
                        to="stories.chapter",
                    ),
                ),
                (
                    "intended_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapter_beats",
                        to="scenes.scene",
                    ),
                ),
                (
                    "pov_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapter_beats",
                        to="characters.character",
                    ),
                ),
                (
                    "timeline_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapter_beats",
                        to="timeline.timelineevent",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("chapter", "order"), name="unique_beat_order")
                ],
            },
        ),
        migrations.CreateModel(
            name="ChapterChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=240)),
                ("completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="stories.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chapter", "order"), name="unique_checklist_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChapterPacingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tension_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tension_notes", models.TextField(blank=True)),
                ("dread_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("dread_notes", models.TextField(blank=True)),
                (
                    "emotional_intimacy_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("emotional_intimacy_notes", models.TextField(blank=True)),
                (
                    "relationship_tension_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("relationship_tension_notes", models.TextField(blank=True)),
                ("pacing_energy_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pacing_energy_notes", models.TextField(blank=True)),
                ("humor_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("humor_notes", models.TextField(blank=True)),
                ("action_intensity_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("action_intensity_notes", models.TextField(blank=True)),
                ("mystery_pressure_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("mystery_pressure_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacing_profile",
                        to="stories.chapter",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tension_score__range", (1, 10)),
                            ("tension_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_tension_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("dread_score__range", (1, 10)),
                            ("dread_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_dread_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("emotional_intimacy_score__range", (1, 10)),
                            ("emotional_intimacy_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_intimacy_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("relationship_tension_score__range", (1, 10)),
                            ("relationship_tension_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_relationship_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pacing_energy_score__range", (1, 10)),
                            ("pacing_energy_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_energy_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("humor_score__range", (1, 10)),
                            ("humor_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_humor_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("action_intensity_score__range", (1, 10)),
                            ("action_intensity_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_action_1_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("mystery_pressure_score__range", (1, 10)),
                            ("mystery_pressure_score__isnull", True),
                            _connector="OR",
                        ),
                        name="pacing_mystery_1_10",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("pov", models.CharField(blank=True, max_length=240)),
                ("scene_function", models.TextField(blank=True)),
                ("previous_context_summary", models.TextField(blank=True)),
                ("character_wants", models.TextField(blank=True)),
                ("primary_conflict", models.TextField(blank=True)),
                ("stakes", models.TextField(blank=True)),
                ("setting", models.TextField(blank=True)),
                ("atmosphere", models.TextField(blank=True)),
                ("blocking_and_beats", models.TextField(blank=True)),
                ("emotional_movement", models.TextField(blank=True)),
                ("continuity_concerns", models.TextField(blank=True)),
                ("thread_and_clue_opportunities", models.TextField(blank=True)),
                ("opening_beat", models.TextField(blank=True)),
                ("ending_hook", models.TextField(blank=True)),
                ("symbolism", models.TextField(blank=True)),
                ("author_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefs",
                        to="scenes.scene",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_briefs",
                        to="scenes.scenerevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("scene",),
                        name="one_active_scene_brief",
                    )
                ],
            },
        ),
    ]
