# Generated by Django 5.2 on 2026-07-11.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="workspace_name_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(choices=[("owner", "Owner")], max_length=16)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("workspace_id", "account_id", "created_at"),
                "indexes": [
                    models.Index(fields=["account", "state"], name="grant_account_state_idx"),
                    models.Index(
                        fields=["workspace", "state"],
                        name="grant_workspace_state_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "active")),
                        fields=("account", "workspace"),
                        name="unique_active_account_workspace_grant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("revoked_at__isnull", True), ("state", "active")),
                            models.Q(("revoked_at__isnull", False), ("state", "revoked")),
                            _connector="OR",
                        ),
                        name="workspace_grant_state_timestamp_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerBootstrap",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_bootstrap",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_bootstrap",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "owner bootstrap completion",
                "verbose_name_plural": "owner bootstrap completions",
            },
        ),
    ]
