from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AITask:
    key: str
    title: str
    category: str
    description: str
    output_sections: tuple[str, ...]
    conversion_targets: tuple[str, ...] = ()


def task(key, title, category, sections, targets=()):
    return AITask(
        key,
        title,
        category,
        f"Use deliberately selected context to {title.lower()}.",
        tuple(sections),
        tuple(targets),
    )


TASKS = {
    item.key: item
    for item in (
        task(
            "story_chat", "Continue Story Chat", "chat", ("Response", "Questions", "Possibilities")
        ),
        task(
            "brainstorm_plot",
            "Plot Seeds",
            "brainstorm",
            ("Direction One", "Direction Two", "Direction Three", "Context Boundaries"),
            ("chapter", "plot_thread", "timeline_event"),
        ),
        task(
            "brainstorm_realm",
            "Realm Builder",
            "brainstorm",
            (
                "Realm Name",
                "Type and Identity",
                "Stability Status",
                "Gate and Access",
                "Atmosphere and Visuals",
                "Notable Features",
                "Current Situation",
                "Environmental Conditions",
                "Story Entry Points",
            ),
            ("location", "region"),
        ),
        task(
            "brainstorm_npc",
            "NPC Generator",
            "brainstorm",
            (
                "Name",
                "Threat Level",
                "Role and Group",
                "Physical Reality",
                "Personality",
                "Immediate Want",
                "Hidden Truth",
                "World Relationship",
                "Story Entry Point",
                "Memorable Detail",
            ),
            ("character",),
        ),
        task(
            "brainstorm_monster",
            "Monster Generator",
            "brainstorm",
            (
                "Name or Designation",
                "Classification",
                "Threat Level",
                "Physical Reality",
                "Behavior and Ecology",
                "World Signature",
                "Weaknesses or Tells",
                "Encounter Scenario",
                "Memorable Detail",
            ),
            ("creature", "character"),
        ),
        task(
            "brainstorm_item",
            "Item Generator",
            "brainstorm",
            (
                "Name",
                "Discipline",
                "Type",
                "Origin",
                "Physical Description",
                "How It Works",
                "Significance",
                "Typical Holder",
                "Story Hook",
                "Memorable Detail",
            ),
            ("item",),
        ),
        task(
            "research_summary",
            "Summarize Research Source",
            "research",
            ("Source Summary", "Useful Details", "Citations", "Questions"),
            ("research_note",),
        ),
        task(
            "research_compare",
            "Compare Research Sources",
            "research",
            (
                "Agreements",
                "Differences",
                "Possible Contradictions",
                "Credibility Notes",
                "Questions",
            ),
            ("research_note",),
        ),
        task(
            "research_story",
            "Apply Research to Story Context",
            "research",
            ("Source-Supported Details", "Story Applications", "Canon Questions", "Citations"),
            ("research_note", "codex", "plot_thread"),
        ),
        task(
            "visual_direction",
            "Develop Visual Direction",
            "research",
            ("Visual Motifs", "Palette", "Mood", "Design Guidance", "Story Use"),
            ("research_note",),
        ),
        task(
            "chapter_reference_brief",
            "Create Chapter Reference Brief",
            "research",
            ("Relevant Research", "Visual References", "Continuity Boundaries", "Citations"),
            ("research_note", "chapter"),
        ),
        task(
            "manuscript_summary",
            "Generate Manuscript Summary",
            "publication",
            ("Summary", "Audience", "Themes", "Source Boundaries"),
            ("manuscript",),
        ),
        task(
            "manuscript_back_cover",
            "Generate Back-Cover Copy",
            "publication",
            ("Hook", "Back-Cover Copy", "Alternate Copy", "Claims to Review"),
            ("manuscript",),
        ),
        task(
            "manuscript_synopsis",
            "Generate Synopsis",
            "publication",
            ("Short Synopsis", "Full Synopsis", "Continuity Notes"),
            ("manuscript",),
        ),
        task(
            "submission_summary",
            "Generate Submission Summary",
            "publication",
            ("Logline", "Summary", "Comparable Positioning", "Review Notes"),
            ("manuscript",),
        ),
        task(
            "publication_readiness",
            "Publication Readiness Review",
            "publication",
            ("Ready Elements", "Possible Issues", "Missing Matter", "Author Decisions"),
            ("manuscript",),
        ),
        task(
            "compilation_consistency",
            "Compilation Consistency Review",
            "publication",
            ("Source-Supported Concerns", "Ordering", "Continuity", "Questions"),
            ("manuscript",),
        ),
        task(
            "chapter_directions",
            "Brainstorm Chapter Directions",
            "chapter",
            ("Current Story Position", "Three Directions", "Tradeoffs", "Continuity Opportunities"),
            ("chapter", "plot_thread"),
        ),
        task(
            "chapter_outline",
            "Build Chapter Outline",
            "chapter",
            ("Chapter Function", "Key Beats", "Scene Breakdown", "Emotional Arc", "Ending Hook"),
            ("chapter_outline",),
        ),
        task(
            "chapter_continuity",
            "What Can Pay Off Here?",
            "chapter",
            ("Relevant Open Threads", "Payoff Opportunities", "Risks", "Questions"),
            ("plot_thread", "clue", "reveal"),
        ),
        task(
            "chapter_pacing",
            "Analyze Chapter Pacing",
            "chapter",
            (
                "Pacing Shape",
                "Tension",
                "Energy",
                "Emotional Intimacy",
                "Humor",
                "Planning Suggestions",
            ),
            ("chapter",),
        ),
        task(
            "chapter_voice",
            "Review Chapter Voice",
            "chapter",
            ("Voice Profile Alignment", "Strengths", "Possible Drift", "Revision Priorities"),
            ("chapter",),
        ),
        task(
            "scene_brief",
            "Build Scene Brief",
            "scene",
            (
                "Scene Function",
                "POV",
                "Character Wants",
                "Main Conflict",
                "Stakes",
                "Setting and Atmosphere",
                "Blocking and Beats",
                "Emotional Movement",
                "Continuity Risks",
                "Opening Beat",
                "Ending Hook",
            ),
        ),
        task(
            "scene_revision",
            "Revision Suggestions",
            "scene",
            ("Source Excerpt", "Concern", "Importance", "Explanation", "Proposed Revision"),
            ("scene_revision",),
        ),
        task(
            "scene_rewrite",
            "Rewrite with Constraints",
            "scene",
            ("Original", "Proposed Text", "Constraint Notes"),
            ("scene_revision",),
        ),
        task(
            "character_deepen",
            "Deepen Character",
            "character",
            (
                "Motivations",
                "Internal Conflict",
                "Contradictions",
                "Relationships",
                "Arc Possibilities",
                "Questions",
            ),
            ("character", "plot_thread"),
        ),
        task(
            "character_fill_description",
            "Fill Character from Description",
            "character",
            (
                "Name",
                "Aliases",
                "Role",
                "Age",
                "Appearance",
                "Personality",
                "Backstory",
                "Goals",
                "Conflicts",
                "Voice",
                "Tags",
                "Ability Suggestions",
                "Relationship Suggestions",
                "Slider Suggestions",
            ),
            ("character", "ability", "relationship"),
        ),
        task(
            "character_evaluation",
            "Evaluate Character",
            "character",
            (
                "Current Summary",
                "Strengths",
                "Weaknesses",
                "Contradictions",
                "Goals versus Behavior",
                "Arc Movement",
                "Relationship Pressure",
                "Ability Continuity",
                "Personality Consistency",
                "Missing Information",
                "Underused Traits",
                "Continuity Risks",
                "Next Developments",
            ),
            ("character", "plot_thread", "ability_stage"),
        ),
        task(
            "character_goals",
            "Develop Goals and Conflicts",
            "character",
            (
                "Goals",
                "Internal Conflicts",
                "External Conflicts",
                "Behavioral Pressure",
                "Questions",
            ),
            ("character", "plot_thread"),
        ),
        task(
            "character_backstory",
            "Develop Character Backstory",
            "character",
            (
                "Origins",
                "Formative Events",
                "Private History",
                "Timeline Possibilities",
                "Canon Questions",
            ),
            ("character", "timeline_event"),
        ),
        task(
            "character_personality",
            "Refine Character Personality",
            "character",
            ("Temperament", "Values", "Fears", "Wants", "Contradictions", "Habits"),
            ("character",),
        ),
        task(
            "character_sliders",
            "Suggest Personality Sliders",
            "character",
            ("Slider Suggestions", "Evidence", "Contradictions to Preserve"),
            ("character",),
        ),
        task(
            "character_voice",
            "Evaluate Character Voice",
            "character",
            ("Voice Markers", "Consistency", "Possible Drift", "Revision Guidance"),
            ("character",),
        ),
        task(
            "character_relationships",
            "Assess Relationship Dynamics",
            "character",
            (
                "Current Dynamics",
                "Pressure Points",
                "Evolution Possibilities",
                "Continuity Questions",
            ),
            ("relationship", "plot_thread"),
        ),
        task(
            "character_arc",
            "Propose Character Arc Progression",
            "character",
            (
                "Current Phase",
                "Turning Points",
                "Change Events",
                "Unresolved Questions",
                "Possible End States",
            ),
            ("character", "plot_thread"),
        ),
        task(
            "character_continuity",
            "Identify Character Continuity Risks",
            "analysis",
            (
                "Supported Facts",
                "Possible Contradictions",
                "Knowledge Boundaries",
                "Ability Risks",
                "Questions",
            ),
            ("character", "knowledge"),
        ),
        task(
            "character_knowledge",
            "What Does This Character Know?",
            "character",
            ("Objective Truth", "Known", "Suspected", "Mistaken Beliefs", "Hidden From Them"),
            ("knowledge",),
        ),
        task(
            "ability_next",
            "Suggest Next Progression Stage",
            "ability",
            (
                "Plausible Stage",
                "Catalyst",
                "Training",
                "Costs",
                "Limitations",
                "Failure Modes",
                "Counters",
                "Narrative Consequences",
                "Endgame Possibilities",
            ),
            ("ability_stage", "ability_event"),
        ),
        task(
            "ability_consistency",
            "Progression Consistency Review",
            "ability",
            (
                "Current Rules",
                "Consistent Elements",
                "Possible Conflicts",
                "Questions",
                "Suggestions",
            ),
        ),
        task(
            "location_develop",
            "Develop Location",
            "world",
            (
                "Identity",
                "History",
                "Atmosphere",
                "Sensory Detail",
                "Hazards",
                "Current State",
                "Story Uses",
            ),
            ("location",),
        ),
        task(
            "region_develop",
            "Develop Region",
            "world",
            ("Geography", "Culture", "Politics", "Conflicts", "Travel", "Historical Layers"),
            ("region",),
        ),
        task(
            "group_develop",
            "Develop Group or Faction",
            "world",
            (
                "Goals",
                "Hidden Goals",
                "Resources",
                "Methods",
                "Internal Structure",
                "Alliances",
                "Enemies",
                "Conflict Possibilities",
            ),
            ("group",),
        ),
        task(
            "codex_develop",
            "Develop Codex Concept",
            "world",
            ("Definition", "Implications", "Related Terms", "Continuity Questions"),
            ("codex",),
        ),
        task(
            "item_generate",
            "Design Item or Artifact",
            "world",
            (
                "Name Options",
                "Origin",
                "Function",
                "Capabilities",
                "Costs",
                "Dangers",
                "Ownership History",
                "Story Importance",
            ),
            ("item",),
        ),
        task(
            "monster_generate",
            "Generate Monster",
            "generator",
            (
                "Name Options",
                "Classification",
                "Appearance",
                "Biology or Nature",
                "Habitat",
                "Behavior",
                "Needs",
                "Abilities",
                "Weaknesses",
                "Signs and Traces",
                "Ecology",
                "Cultural Significance",
                "Encounter Concepts",
                "Escalation",
                "Narrative Role",
            ),
            ("creature", "character"),
        ),
        task(
            "npc_generate",
            "Generate NPC",
            "generator",
            (
                "Name Options",
                "Role",
                "Motivation",
                "Appearance",
                "Personality",
                "Voice",
                "Resources",
                "Relationships",
                "Secrets",
                "Conflict Potential",
                "Entry Points",
                "Long-term Arc",
            ),
            ("character",),
        ),
        task(
            "continuity_review",
            "Continuity Review",
            "continuity",
            (
                "Source-supported Concerns",
                "Possible Concerns",
                "Questions for Author",
                "Suggestions",
            ),
            ("plot_thread", "clue", "reveal", "knowledge"),
        ),
        task(
            "thread_payoff",
            "Thread Payoff Opportunities",
            "continuity",
            ("Open Threads", "Promises", "Payoff Options", "Timing Risks", "Questions"),
            ("plot_thread", "reveal"),
        ),
        task(
            "timeline_review",
            "Timeline Contradiction Review",
            "timeline",
            (
                "Chronology",
                "Reader Order",
                "Possible Ordering Issues",
                "Missing Transitions",
                "Questions",
            ),
            ("timeline_event", "event_relation"),
        ),
        task(
            "timeline_summary",
            "Chronology Summary",
            "timeline",
            (
                "Established Events",
                "Uncertain Events",
                "Causal Chain",
                "Reader Exposure",
                "Open Questions",
            ),
            ("timeline_event",),
        ),
        task(
            "deck_interpret",
            "Interpret Draw in World Context",
            "deck",
            (
                "Card and Position Reading",
                "World-specific Interpretation",
                "Three Story Directions",
                "Continuity Fit",
                "Questions",
            ),
            ("draw_interpretation", "plot_thread"),
        ),
        task(
            "voice_analyze",
            "Analyze Voice Sample",
            "voice",
            (
                "Prose Guidance",
                "Dialogue Guidance",
                "Sentence Rhythm",
                "Paragraph Rhythm",
                "Diction",
                "Imagery",
                "Humor",
                "Emotional Distance",
                "Exposition",
                "Prohibited Tendencies",
                "Intentional Quirks",
            ),
            ("voice_profile",),
        ),
        task(
            "editorial_developmental",
            "Developmental Review",
            "editorial",
            ("Source Excerpt", "Concern", "Importance", "Explanation", "Suggestion"),
        ),
        task(
            "editorial_tighten",
            "Tighten Passage",
            "editorial",
            ("Original", "Proposed Text", "Changes and Voice Preservation"),
            ("scene_revision",),
        ),
        task(
            "editorial_tension",
            "Increase Tension",
            "editorial",
            ("Original", "Proposed Text", "Tension Changes", "Voice Preservation"),
            ("scene_revision",),
        ),
        task(
            "deslop_pacing_analysis",
            "De-Slop: Pacing Analysis",
            "editorial",
            ("Source Excerpt", "Pacing Concerns", "Rhythm Risks", "Revision Plan"),
        ),
        task(
            "deslop_pacing_rewrite",
            "De-Slop: Pacing Rewrite",
            "editorial",
            ("Original", "Proposed Text", "Pacing Changes", "Voice Preservation"),
            ("scene_revision",),
        ),
        task(
            "deslop_line_analysis",
            "De-Slop: Line Analysis",
            "editorial",
            ("Source Excerpt", "Line-Level Habits", "Repetition", "Revision Plan"),
        ),
        task(
            "deslop_line_rewrite",
            "De-Slop: Line Rewrite",
            "editorial",
            ("Original", "Proposed Text", "Line Changes", "Voice Preservation"),
            ("scene_revision",),
        ),
        task(
            "deslop_tendency_analysis",
            "De-Slop: AI-Tendency Analysis",
            "editorial",
            ("Source Excerpt", "Possible Tendencies", "Evidence", "Author Questions"),
        ),
        task(
            "deslop_final_rewrite",
            "De-Slop: Final Voice-Preserving Rewrite",
            "editorial",
            ("Original", "Proposed Text", "Resolved Tendencies", "Voice Preservation"),
            ("scene_revision",),
        ),
    )
}

CATEGORIES = tuple(dict.fromkeys(item.category for item in TASKS.values()))


def get_task(key):
    return TASKS[key]
