# Generated by Django 5.2.16 on 2026-07-12 00:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("owner_bootstrap_succeeded", "Owner Bootstrap Succeeded"),
                            ("owner_bootstrap_rejected", "Owner Bootstrap Rejected"),
                            ("login_succeeded", "Login Succeeded"),
                            ("login_failed", "Login Failed"),
                            ("logout_succeeded", "Logout Succeeded"),
                            ("workspace_access_denied", "Workspace Access Denied"),
                            ("scene_access_denied", "Scene Access Denied"),
                            ("scene_save_conflict", "Scene Save Conflict"),
                            ("scene_save_key_conflict", "Scene Save Key Conflict"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("denied", "Denied"),
                            ("conflicted", "Conflicted"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "target_category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("account", "Account"),
                            ("session", "Session"),
                            ("workspace", "Workspace"),
                            ("scene", "Scene"),
                            ("bootstrap", "Bootstrap"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.CharField(max_length=32)),
                (
                    "service_role",
                    models.CharField(
                        choices=[("web", "Web"), ("operator", "Operator")], max_length=16
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("invalid_credentials", "Invalid Credentials"),
                            ("inaccessible", "Inaccessible"),
                            ("inactive_grant", "Inactive Grant"),
                            ("optimistic_concurrency", "Optimistic Concurrency"),
                            ("idempotency_key_reuse", "Idempotency Key Reuse"),
                            ("existing_state", "Existing State"),
                            ("invalid_input", "Invalid Input"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"], name="security_type_time_idx"
                    ),
                    models.Index(
                        fields=["outcome", "occurred_at"], name="security_outcome_time_idx"
                    ),
                    models.Index(fields=["workspace", "occurred_at"], name="security_ws_time_idx"),
                    models.Index(fields=["actor", "occurred_at"], name="security_actor_time_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_type__in",
                                (
                                    "owner_bootstrap_succeeded",
                                    "owner_bootstrap_rejected",
                                    "login_succeeded",
                                    "login_failed",
                                    "logout_succeeded",
                                    "workspace_access_denied",
                                    "scene_access_denied",
                                    "scene_save_conflict",
                                    "scene_save_key_conflict",
                                ),
                            )
                        ),
                        name="security_event_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome__in", ("succeeded", "denied", "conflicted", "failed"))
                        ),
                        name="security_event_outcome_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "target_category__in",
                                (
                                    "authentication",
                                    "account",
                                    "session",
                                    "workspace",
                                    "scene",
                                    "bootstrap",
                                ),
                            )
                        ),
                        name="security_event_target_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("service_role__in", ("web", "operator"))),
                        name="security_event_service_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason__in",
                                (
                                    "",
                                    "invalid_credentials",
                                    "inaccessible",
                                    "inactive_grant",
                                    "optimistic_concurrency",
                                    "idempotency_key_reuse",
                                    "existing_state",
                                    "invalid_input",
                                ),
                            )
                        ),
                        name="security_event_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("correlation_id__regex", "^[0-9a-f]{32}$")),
                        name="security_event_correlation_valid",
                    ),
                ],
            },
        ),
    ]
