# Generated by Django 5.2.16 on 2026-07-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("owner_bootstrap_succeeded", "Owner Bootstrap Succeeded"),
                    ("owner_bootstrap_rejected", "Owner Bootstrap Rejected"),
                    ("login_succeeded", "Login Succeeded"),
                    ("login_failed", "Login Failed"),
                    ("logout_succeeded", "Logout Succeeded"),
                    ("workspace_access_denied", "Workspace Access Denied"),
                    ("scene_access_denied", "Scene Access Denied"),
                    ("scene_save_conflict", "Scene Save Conflict"),
                    ("scene_save_key_conflict", "Scene Save Key Conflict"),
                    ("webauthn_enrolled", "Webauthn Enrolled"),
                    ("webauthn_used", "Webauthn Used"),
                    ("webauthn_anomaly", "Webauthn Anomaly"),
                    ("totp_enrolled", "Totp Enrolled"),
                    ("totp_used", "Totp Used"),
                    ("recovery_codes_generated", "Recovery Codes Generated"),
                    ("recovery_code_used", "Recovery Code Used"),
                    ("mfa_succeeded", "Mfa Succeeded"),
                    ("mfa_failed", "Mfa Failed"),
                    ("session_revoked", "Session Revoked"),
                    ("password_changed", "Password Changed"),
                    ("owner_recovery_initiated", "Owner Recovery Initiated"),
                    ("authentication_throttled", "Authentication Throttled"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("invalid_credentials", "Invalid Credentials"),
                    ("inaccessible", "Inaccessible"),
                    ("inactive_grant", "Inactive Grant"),
                    ("optimistic_concurrency", "Optimistic Concurrency"),
                    ("idempotency_key_reuse", "Idempotency Key Reuse"),
                    ("existing_state", "Existing State"),
                    ("invalid_input", "Invalid Input"),
                    ("invalid_mfa", "Invalid Mfa"),
                    ("replay", "Replay"),
                    ("anomalous_counter", "Anomalous Counter"),
                    ("throttled", "Throttled"),
                    ("recovery", "Recovery"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="target_category",
            field=models.CharField(
                choices=[
                    ("authentication", "Authentication"),
                    ("account", "Account"),
                    ("session", "Session"),
                    ("workspace", "Workspace"),
                    ("scene", "Scene"),
                    ("bootstrap", "Bootstrap"),
                    ("mfa_factor", "Mfa Factor"),
                ],
                max_length=24,
            ),
        ),
    ]
