# Generated by Django 5.2.16 on 2026-07-12 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security_events", "0002_alter_securityevent_event_type_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="securityevent",
            name="security_event_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="securityevent",
            name="security_event_target_valid",
        ),
        migrations.RemoveConstraint(
            model_name="securityevent",
            name="security_event_reason_valid",
        ),
        migrations.AddConstraint(
            model_name="securityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        (
                            "owner_bootstrap_succeeded",
                            "owner_bootstrap_rejected",
                            "login_succeeded",
                            "login_failed",
                            "logout_succeeded",
                            "workspace_access_denied",
                            "scene_access_denied",
                            "scene_save_conflict",
                            "scene_save_key_conflict",
                            "webauthn_enrolled",
                            "webauthn_used",
                            "webauthn_anomaly",
                            "totp_enrolled",
                            "totp_used",
                            "recovery_codes_generated",
                            "recovery_code_used",
                            "mfa_succeeded",
                            "mfa_failed",
                            "session_revoked",
                            "password_changed",
                            "owner_recovery_initiated",
                            "authentication_throttled",
                        ),
                    )
                ),
                name="security_event_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_category__in",
                        (
                            "authentication",
                            "account",
                            "session",
                            "workspace",
                            "scene",
                            "bootstrap",
                            "mfa_factor",
                        ),
                    )
                ),
                name="security_event_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason__in",
                        (
                            "",
                            "invalid_credentials",
                            "inaccessible",
                            "inactive_grant",
                            "optimistic_concurrency",
                            "idempotency_key_reuse",
                            "existing_state",
                            "invalid_input",
                            "invalid_mfa",
                            "replay",
                            "anomalous_counter",
                            "throttled",
                            "recovery",
                        ),
                    )
                ),
                name="security_event_reason_valid",
            ),
        ),
    ]
