# Generated by Django 5.2.16 on 2026-07-12 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security_events", "0003_remove_securityevent_security_event_type_valid_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="securityevent",
            name="security_event_type_valid",
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("owner_bootstrap_succeeded", "Owner Bootstrap Succeeded"),
                    ("owner_bootstrap_rejected", "Owner Bootstrap Rejected"),
                    ("login_succeeded", "Login Succeeded"),
                    ("login_failed", "Login Failed"),
                    ("logout_succeeded", "Logout Succeeded"),
                    ("workspace_access_denied", "Workspace Access Denied"),
                    ("scene_access_denied", "Scene Access Denied"),
                    ("scene_save_conflict", "Scene Save Conflict"),
                    ("scene_save_key_conflict", "Scene Save Key Conflict"),
                    ("webauthn_enrolled", "Webauthn Enrolled"),
                    ("webauthn_used", "Webauthn Used"),
                    ("webauthn_anomaly", "Webauthn Anomaly"),
                    ("webauthn_revoked", "Webauthn Revoked"),
                    ("totp_enrolled", "Totp Enrolled"),
                    ("totp_used", "Totp Used"),
                    ("totp_revoked", "Totp Revoked"),
                    ("recovery_codes_generated", "Recovery Codes Generated"),
                    ("recovery_code_used", "Recovery Code Used"),
                    ("mfa_succeeded", "Mfa Succeeded"),
                    ("mfa_failed", "Mfa Failed"),
                    ("session_revoked", "Session Revoked"),
                    ("password_changed", "Password Changed"),
                    ("owner_recovery_initiated", "Owner Recovery Initiated"),
                    ("authentication_throttled", "Authentication Throttled"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="securityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        (
                            "owner_bootstrap_succeeded",
                            "owner_bootstrap_rejected",
                            "login_succeeded",
                            "login_failed",
                            "logout_succeeded",
                            "workspace_access_denied",
                            "scene_access_denied",
                            "scene_save_conflict",
                            "scene_save_key_conflict",
                            "webauthn_enrolled",
                            "webauthn_used",
                            "webauthn_anomaly",
                            "webauthn_revoked",
                            "totp_enrolled",
                            "totp_used",
                            "totp_revoked",
                            "recovery_codes_generated",
                            "recovery_code_used",
                            "mfa_succeeded",
                            "mfa_failed",
                            "session_revoked",
                            "password_changed",
                            "owner_recovery_initiated",
                            "authentication_throttled",
                        ),
                    )
                ),
                name="security_event_type_valid",
            ),
        ),
    ]
