# Generated by Django 5.2.16 on 2026-07-12 02:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0003_remove_job_job_type_valid_and_more"),
        ("scenes", "0004_remove_mutationoperation_mutation_operation_type_valid_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_system", models.CharField(default="legacy_story_engine", max_length=32)),
                ("source_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("source_size", models.PositiveBigIntegerField()),
                (
                    "transformation_version",
                    models.CharField(default="story-engine-scenes-v1", max_length=32),
                ),
                ("staging_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "approved_staging_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("validating", "Validating"),
                            ("staged", "Staged"),
                            ("validation_failed", "Validation failed"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("applying", "Applying"),
                            ("applied", "Applied"),
                            ("failed_terminal", "Failed terminal"),
                            ("cancelled", "Cancelled"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="created",
                        max_length=24,
                    ),
                ),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("transformed_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                (
                    "failure_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("invalid_source", "Invalid source"),
                            ("authorization", "Authorization"),
                            ("conflict", "Conflict"),
                            ("integrity", "Integrity"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("quarantined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staging_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="jobs.job",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_system", models.CharField(default="legacy_story_engine", max_length=32)),
                (
                    "source_entity_type",
                    models.CharField(
                        choices=[("scene", "Scene"), ("revision", "Revision")], max_length=16
                    ),
                ),
                ("source_identifier", models.CharField(max_length=128)),
                (
                    "target_entity_type",
                    models.CharField(
                        choices=[("scene", "Scene"), ("revision", "Revision")], max_length=16
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[("proposed", "Proposed"), ("applied", "Applied")],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappings",
                        to="legacy_imports.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_entity_type", models.CharField(max_length=32)),
                ("source_identifier", models.CharField(blank=True, max_length=128)),
                ("issue_code", models.CharField(max_length=48)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("transformed", "Transformed"),
                            ("warning", "Warning"),
                            ("duplicate_candidate", "Duplicate candidate"),
                            ("conflict", "Conflict"),
                            ("unsupported", "Unsupported"),
                            ("rejected", "Rejected"),
                            ("malformed", "Malformed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("field_category", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="legacy_imports.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("transformation_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provenance",
                        to="legacy_imports.importbatch",
                    ),
                ),
                (
                    "mapping",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provenance",
                        to="legacy_imports.identitymapping",
                    ),
                ),
                (
                    "mutation_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_provenance",
                        to="scenes.mutationoperation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StagedScene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_identifier", models.CharField(max_length=128)),
                ("proposed_scene_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("proposed_title", models.CharField(max_length=200)),
                ("proposed_lifecycle", models.CharField(max_length=16)),
                ("proposed_ordering", models.PositiveBigIntegerField()),
                ("current_source_revision", models.CharField(max_length=128)),
                ("source_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("warning", "Warning"),
                            ("blocked", "Blocked"),
                            ("applied", "Applied"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_scenes",
                        to="legacy_imports.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StagedRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_identifier", models.CharField(max_length=128)),
                ("proposed_revision_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("proposed_revision_number", models.PositiveBigIntegerField()),
                ("content", models.TextField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("target_content_hash", models.CharField(max_length=64)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "chronology",
                    models.CharField(
                        choices=[("trusted", "Trusted"), ("uncertain", "Uncertain")], max_length=16
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_revisions",
                        to="legacy_imports.importbatch",
                    ),
                ),
                (
                    "staged_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_revisions",
                        to="legacy_imports.stagedscene",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["workspace", "state"], name="import_batch_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("workspace", "source_fingerprint", "transformation_version"),
                name="unique_import_source_transformation",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="import_source_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_schema_version", 1), ("source_system", "legacy_story_engine")
                ),
                name="import_source_format_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("transformation_version", "story-engine-scenes-v1")),
                name="import_transformation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "created",
                            "validating",
                            "staged",
                            "validation_failed",
                            "awaiting_approval",
                            "approved",
                            "applying",
                            "applied",
                            "failed_terminal",
                            "cancelled",
                            "quarantined",
                        ),
                    )
                ),
                name="import_batch_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "failure_classification__in",
                        ("", "invalid_source", "authorization", "conflict", "integrity"),
                    )
                ),
                name="import_batch_failure_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("staging_fingerprint", ""),
                    ("staging_fingerprint__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="import_staging_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_staging_fingerprint", ""),
                    ("approved_staging_fingerprint__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="import_approved_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitymapping",
            constraint=models.UniqueConstraint(
                fields=("batch", "source_entity_type", "source_identifier"),
                name="unique_import_source_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitymapping",
            constraint=models.UniqueConstraint(
                fields=("batch", "target_entity_type", "target_uuid"),
                name="unique_import_target_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitymapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_system", "legacy_story_engine")),
                name="mapping_source_system_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitymapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_entity_type__in", ("scene", "revision")),
                    ("target_entity_type__in", ("scene", "revision")),
                ),
                name="mapping_entity_types_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitymapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("proposed", "applied"))),
                name="mapping_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "severity__in",
                        (
                            "transformed",
                            "warning",
                            "duplicate_candidate",
                            "conflict",
                            "unsupported",
                            "rejected",
                            "malformed",
                        ),
                    )
                ),
                name="import_finding_severity_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedscene",
            constraint=models.UniqueConstraint(
                fields=("batch", "source_identifier"), name="unique_staged_scene_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedscene",
            constraint=models.UniqueConstraint(
                fields=("batch", "proposed_scene_id"), name="unique_staged_scene_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedscene",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_lifecycle__in", ("active", "archived", "trashed"))),
                name="staged_scene_lifecycle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedscene",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("accepted", "warning", "blocked", "applied"))),
                name="staged_scene_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedscene",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="staged_scene_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.UniqueConstraint(
                fields=("batch", "staged_scene", "source_identifier"),
                name="unique_staged_revision_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.UniqueConstraint(
                fields=("batch", "proposed_revision_id"), name="unique_staged_revision_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.UniqueConstraint(
                fields=("staged_scene", "proposed_revision_number"),
                name="unique_staged_revision_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("staged_scene",),
                name="one_current_staged_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("chronology__in", ("trusted", "uncertain"))),
                name="staged_revision_chronology_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_content_hash__regex", "^[0-9a-f]{64}$"),
                    ("target_content_hash__regex", "^[0-9a-f]{64}$"),
                ),
                name="staged_revision_hashes_valid",
            ),
        ),
    ]
