# Generated by Django 5.2.16 on 2026-07-18 02:06

import uuid

import django.db.models.deletion
from django.db import migrations, models

import publishing.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0005_remove_job_job_type_valid_and_more"),
        ("library", "0002_researchsource_tags"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0003_chapter_editorial_concerns_chapter_final_check_notes_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                (
                    "manuscript_type",
                    models.CharField(
                        choices=[
                            ("full_work", "Full Work"),
                            ("volume", "Volume"),
                            ("arc", "Arc"),
                            ("chapter_selection", "Chapter Selection"),
                            ("short_story_collection", "Short Story Collection"),
                            ("web_serial_reading_copy", "Web Serial Reading Copy"),
                            ("screenplay", "Screenplay"),
                            ("stage_play", "Stage Play"),
                            ("comic_script", "Comic Script"),
                            ("custom", "Custom"),
                        ],
                        default="full_work",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready for review"),
                            ("approved", "Approved"),
                            ("exported", "Exported"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("title_override", models.CharField(blank=True, max_length=240)),
                ("subtitle_override", models.CharField(blank=True, max_length=240)),
                ("author_name_override", models.CharField(blank=True, max_length=240)),
                ("edition_label", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("front_matter_notes", models.TextField(blank=True)),
                ("back_matter_notes", models.TextField(blank=True)),
                ("formatting_profile", models.CharField(default="clean_manuscript", max_length=40)),
                ("formatting_overrides", models.JSONField(blank=True, default=dict)),
                ("include_chapter_labels", models.BooleanField(default=True)),
                ("include_scene_titles", models.BooleanField(default=False)),
                ("include_chapter_summaries", models.BooleanField(default=False)),
                ("include_scene_breaks", models.BooleanField(default=True)),
                ("include_artwork", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuscripts",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuscripts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ManuscriptEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("title_page", "Title Page"),
                            ("copyright_page", "Copyright Page"),
                            ("dedication", "Dedication"),
                            ("epigraph", "Epigraph"),
                            ("table_of_contents", "Table Of Contents"),
                            ("volume_heading", "Volume Heading"),
                            ("arc_heading", "Arc Heading"),
                            ("chapter", "Chapter"),
                            ("scene", "Scene"),
                            ("custom_prose", "Custom Prose"),
                            ("acknowledgments", "Acknowledgments"),
                            ("author_note", "Author Note"),
                            ("glossary", "Glossary"),
                            ("appendix", "Appendix"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("custom_heading", models.CharField(blank=True, max_length=240)),
                ("custom_text", models.TextField(blank=True)),
                ("include", models.BooleanField(default=True)),
                (
                    "page_break_behavior",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("before", "Before"),
                            ("after", "After"),
                            ("none", "None"),
                        ],
                        default="auto",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.arc",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.chapter",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scenes.scene",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.volume",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="publishing.manuscriptproject",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ManuscriptArtworkPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("cover", "Cover"),
                            ("title_page", "Title page"),
                            ("chapter", "Chapter illustration"),
                            ("map", "Map"),
                            ("divider", "Section divider"),
                            ("appendix", "Appendix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("alt_text_override", models.TextField(blank=True)),
                ("scaling", models.CharField(default="fit", max_length=20)),
                ("page_break_behavior", models.CharField(default="auto", max_length=12)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuscript_placements",
                        to="library.artworkasset",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_placements",
                        to="publishing.manuscriptentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_placements",
                        to="publishing.manuscriptproject",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("text", "Plain text"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("docx", "DOCX"),
                            ("pdf", "PDF"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(blank=True, upload_to=publishing.models.export_upload_path),
                ),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("compiled_manuscript_checksum", models.CharField(blank=True, max_length=64)),
                ("source_snapshot", models.JSONField(default=dict)),
                ("warning_report", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_record",
                        to="jobs.job",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="publishing.manuscriptproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ManuscriptSceneSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "selection_mode",
                    models.CharField(
                        choices=[
                            ("latest", "Latest current Revision"),
                            ("explicit", "Explicit Revision"),
                            ("locked", "Locked at export"),
                            ("published", "Published Revision"),
                        ],
                        default="latest",
                        max_length=16,
                    ),
                ),
                ("locked", models.BooleanField(default=False)),
                ("source_checksum", models.CharField(max_length=64)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_selection",
                        to="publishing.manuscriptentry",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuscript_selections",
                        to="scenes.scene",
                    ),
                ),
                (
                    "selected_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuscript_selections",
                        to="scenes.scenerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("web_serial_chapter", "Web Serial Chapter"),
                            ("short_story", "Short Story"),
                            ("novella", "Novella"),
                            ("novel", "Novel"),
                            ("screenplay", "Screenplay"),
                            ("comic_issue", "Comic Issue"),
                            ("collection", "Collection"),
                            ("private_reading_copy", "Private Reading Copy"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("drafting", "Drafting"),
                            ("ready", "Ready"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("revised", "Revised"),
                            ("withdrawn", "Withdrawn"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("platform_label", models.CharField(blank=True, max_length=120)),
                ("planned_date", models.DateField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("public_title", models.CharField(max_length=240)),
                ("public_url", models.URLField(blank=True)),
                ("edition", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("revision_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.arc",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="stories.chapter",
                    ),
                ),
                (
                    "export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="publishing.exportrecord",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="publishing.manuscriptproject",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.volume",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("planned_date", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ManuscriptGlossaryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("codex", "Codex entry"),
                            ("character", "Character"),
                            ("group", "Group"),
                            ("location", "Location"),
                            ("region", "Region"),
                            ("item", "Item"),
                            ("creature", "Creature"),
                            ("timeline_event", "Timeline Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("display_name", models.CharField(max_length=240)),
                ("display_summary", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_entries",
                        to="publishing.manuscriptproject",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "display_name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "target_type", "target_id"),
                        name="manuscript_glossary_target_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="manuscriptentry",
            constraint=models.UniqueConstraint(
                fields=("project", "order"), name="manuscript_entry_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="manuscriptartworkplacement",
            constraint=models.UniqueConstraint(
                fields=("project", "artwork", "placement", "entry"),
                name="manuscript_artwork_use_unique",
                nulls_distinct=False,
            ),
        ),
    ]
