# Generated by Django 5.2.16 on 2026-07-18 04:03

from django.db import migrations, models

import publishing.models
import strange_novelty.private_storage


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrecord",
            name="file",
            field=models.FileField(
                blank=True,
                storage=strange_novelty.private_storage.private_export_storage,
                upload_to=publishing.models.export_upload_path,
            ),
        ),
    ]
