# Generated by Django 5.2.16 on 2026-07-12 02:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0003_remove_job_job_type_valid_and_more"),
        ("scenes", "0004_remove_mutationoperation_mutation_operation_type_valid_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_scene_version", models.PositiveBigIntegerField()),
                ("source_content_hash", models.CharField(max_length=64)),
                (
                    "capability",
                    models.CharField(default="scene_revision_suggestion", max_length=32),
                ),
                ("prompt_template", models.CharField(default="scene-review", max_length=32)),
                ("prompt_template_version", models.CharField(default="v1", max_length=16)),
                ("configuration_version", models.CharField(default="ai-scene-v1", max_length=32)),
                ("instruction", models.TextField(max_length=1000)),
                ("instruction_hash", models.CharField(max_length=64)),
                ("provider", models.CharField(default="local_fake", max_length=32)),
                ("requested_model", models.CharField(default="deterministic-v1", max_length=32)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("maximum_output_characters", models.PositiveIntegerField(default=1000000)),
                ("failure_classification", models.CharField(blank=True, default="", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("quarantined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_request",
                        to="jobs.job",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_requests",
                        to="scenes.scene",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_requests",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIContextManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_scene_version", models.PositiveBigIntegerField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("capability", models.CharField(max_length=32)),
                ("prompt_template", models.CharField(max_length=32)),
                ("prompt_template_version", models.CharField(max_length=16)),
                ("configuration_version", models.CharField(max_length=32)),
                (
                    "context_construction_version",
                    models.CharField(default="single-scene-v1", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_manifests",
                        to="scenes.scene",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_manifests",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_manifests",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_manifest",
                        to="ai_assistance.airequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_scene_version", models.PositiveBigIntegerField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("original_output", models.TextField(max_length=1000000)),
                ("review_text", models.TextField(max_length=1000000)),
                ("output_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("model_classification", models.CharField(max_length=32)),
                ("prompt_template", models.CharField(max_length=32)),
                ("prompt_template_version", models.CharField(max_length=16)),
                (
                    "provider_operation_identifier",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("input_units", models.PositiveIntegerField(default=0)),
                ("output_units", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("quarantined_at", models.DateTimeField(blank=True, null=True)),
                ("resulting_scene_version", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "disposition_classification",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suggestion",
                        to="ai_assistance.airequest",
                    ),
                ),
                (
                    "resulting_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_ai_suggestions",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestions",
                        to="scenes.scene",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestions",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AISuggestionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("applied_text_hash", models.CharField(max_length=64)),
                ("human_edited", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mutation_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_application_provenance",
                        to="scenes.mutationoperation",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_application_provenance",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "suggestion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_provenance",
                        to="ai_assistance.aisuggestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEffect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("operation_identifier", models.CharField(blank=True, default="", max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("intended", "Intended"),
                            ("known_success", "Known success"),
                            ("known_failure", "Known failure"),
                            ("ambiguous", "Ambiguous"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "ambiguity_classification",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("requested_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_effects",
                        to="jobs.jobattempt",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_effects",
                        to="ai_assistance.airequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(fields=["workspace", "state"], name="ai_request_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="airequest",
            constraint=models.UniqueConstraint(
                fields=("workspace", "requested_by", "idempotency_key"),
                name="unique_ai_request_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="airequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_content_hash__regex", "^[0-9a-f]{64}$"),
                    ("instruction_hash__regex", "^[0-9a-f]{64}$"),
                    ("request_fingerprint__regex", "^[0-9a-f]{64}$"),
                ),
                name="ai_request_hashes_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="airequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "scene_revision_suggestion"),
                    ("configuration_version", "ai-scene-v1"),
                    ("prompt_template", "scene-review"),
                    ("prompt_template_version", "v1"),
                ),
                name="ai_request_versions_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="airequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "queued",
                            "running",
                            "completed",
                            "failed",
                            "cancelled",
                            "expired",
                            "quarantined",
                        ),
                    )
                ),
                name="ai_request_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="airequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[A-Za-z0-9._~-]{16,128}$")),
                name="ai_request_key_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["workspace", "state"], name="ai_suggestion_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="aisuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "pending",
                            "ready",
                            "rejected",
                            "applied",
                            "expired",
                            "failed",
                            "quarantined",
                        ),
                    )
                ),
                name="ai_suggestion_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aisuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_content_hash__regex", "^[0-9a-f]{64}$"),
                    ("output_hash__regex", "^[0-9a-f]{64}$"),
                ),
                name="ai_suggestion_hashes_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providereffect",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_attempt__isnull", False)),
                fields=("request", "job_attempt"),
                name="unique_ai_effect_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="providereffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        ("intended", "known_success", "known_failure", "ambiguous", "cancelled"),
                    )
                ),
                name="provider_effect_outcome_valid",
            ),
        ),
    ]
