# Generated by Django 5.2.16 on 2026-07-17 23:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistance", "0001_initial"),
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("continuity", "0002_secretchapterlink_secretcharacterlink_and_more"),
        ("decks", "0003_saveddraw_selected_categories_and_more"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("timeline", "0001_initial"),
        ("workspaces", "0001_initial"),
        ("worldbuilding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContextPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("author_instructions", models.TextField(blank=True)),
                ("tone_guidance", models.TextField(blank=True)),
                ("genre_guidance", models.TextField(blank=True)),
                ("adult_audience_guidance", models.TextField(blank=True)),
                ("exclusions", models.TextField(blank=True)),
                ("prioritization_notes", models.TextField(blank=True)),
                (
                    "detail_level",
                    models.CharField(
                        choices=[("concise", "Concise"), ("detailed", "Detailed")],
                        default="concise",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_packs",
                        to="stories.chapter",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_packs",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_packs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("pinned_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_chat_sessions",
                        to="stories.chapter",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_chat_sessions",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_chat_sessions",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "context_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_sessions",
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AICreativeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_key", models.CharField(max_length=80)),
                ("instruction", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("model_identifier", models.CharField(max_length=160)),
                ("assembly_version", models.CharField(default="context-v1", max_length=32)),
                ("context_snapshot", models.JSONField(default=dict)),
                ("assembled_context", models.TextField()),
                ("context_hash", models.CharField(max_length=64)),
                ("omission_report", models.JSONField(default=list)),
                ("provider_metadata", models.JSONField(default=dict)),
                ("failure_classification", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "context_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_creative_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_creative_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AICreativeSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_output", models.TextField()),
                ("reviewed_output", models.TextField()),
                ("structured_output", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("editing", "Editing"),
                            ("accepted", "Accepted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("stale", "Stale"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suggestion",
                        to="ai_assistance.aicreativerequest",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_creative_suggestions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AICreativeConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.UUIDField()),
                ("action", models.CharField(default="create", max_length=24)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions",
                        to="ai_assistance.aicreativesuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("assistant", "Assistant"),
                            ("system", "Context summary"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("provenance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistance.aichatsession",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_messages",
                        to="ai_assistance.aicreativerequest",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_messages",
                        to="ai_assistance.aicreativesuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("source_notes", models.TextField(blank=True)),
                ("prose_guidance", models.TextField(blank=True)),
                ("dialogue_guidance", models.TextField(blank=True)),
                ("sentence_rhythm", models.TextField(blank=True)),
                ("paragraph_rhythm", models.TextField(blank=True)),
                ("diction", models.TextField(blank=True)),
                ("imagery", models.TextField(blank=True)),
                ("humor", models.TextField(blank=True)),
                ("emotional_distance", models.TextField(blank=True)),
                ("exposition_approach", models.TextField(blank=True)),
                ("prohibited_tendencies", models.TextField(blank=True)),
                ("intentional_quirks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_profiles",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_profiles",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.AddField(
            model_name="aicontextpack",
            name="voice_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="context_packs",
                to="ai_assistance.voiceprofile",
            ),
        ),
        migrations.CreateModel(
            name="AIContextLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "location"), name="ai_pack_location_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "item"), name="ai_pack_item_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextInterpretationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interpretation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="decks.drawinterpretation",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "interpretation"), name="ai_pack_interpretation_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "group"), name="ai_pack_group_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextDrawLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="decks.saveddraw",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "draw"), name="ai_pack_draw_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextCreatureLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "creature"), name="ai_pack_creature_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "codex"), name="ai_pack_codex_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextClueLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.threadclue",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "clue"), name="ai_pack_clue_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="characters.character",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "character"), name="ai_pack_character_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextCharacterKnowledgeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.characterknowledgerecord",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "character_knowledge"),
                        name="ai_pack_character_knowledge_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextCardLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="decks.deckcard",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "card"), name="ai_pack_card_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextArcLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="stories.arc",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "arc"), name="ai_pack_arc_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextAbilityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="characters.ability",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "ability"), name="ai_pack_ability_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextReaderKnowledgeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "reader_knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.readerknowledgerecord",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "reader_knowledge"), name="ai_pack_reader_knowledge_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="worldbuilding.region",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "region"), name="ai_pack_region_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextRevealLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "reveal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.threadreveal",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "reveal"), name="ai_pack_reveal_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextSceneLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "scene"), name="ai_pack_scene_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextSecretLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.secret",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "secret"), name="ai_pack_secret_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextThreadLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="continuity.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "thread"), name="ai_pack_thread_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextTimelineEventLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "timeline_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="timeline.timelineevent",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "timeline_event"), name="ai_pack_timeline_event_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextTimelineLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="timeline.timeline",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pack", "timeline"), name="ai_pack_timeline_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIContextVolumeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_context_links",
                        to="stories.volume",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("pack", "volume"), name="ai_pack_volume_uniq")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aicreativerequest",
            index=models.Index(fields=["workspace", "state"], name="creative_req_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="voiceprofile",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="voice_ws_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextpack",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="ai_pack_ws_name_uniq"
            ),
        ),
    ]
