# Generated by Django 5.2.16 on 2026-07-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistance", "0003_aicontextartworklink_aicontextcollectionlink_and_more"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicontextartworklink",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_context_links",
                to="library.artworkasset",
            ),
        ),
        migrations.AddField(
            model_name="aicontextartworklink",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_assistance.aicontextpack"
            ),
        ),
        migrations.AddField(
            model_name="aicontextcollectionlink",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_context_links",
                to="library.librarycollection",
            ),
        ),
        migrations.AddField(
            model_name="aicontextcollectionlink",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_assistance.aicontextpack"
            ),
        ),
        migrations.AddField(
            model_name="aicontextresearchnotelink",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_assistance.aicontextpack"
            ),
        ),
        migrations.AddField(
            model_name="aicontextresearchnotelink",
            name="research_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_context_links",
                to="library.researchnote",
            ),
        ),
        migrations.AddField(
            model_name="aicontextresearchsourcelink",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_assistance.aicontextpack"
            ),
        ),
        migrations.AddField(
            model_name="aicontextresearchsourcelink",
            name="research_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_context_links",
                to="library.researchsource",
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextartworklink",
            constraint=models.UniqueConstraint(
                fields=("pack", "artwork"), name="ai_pack_artwork_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextcollectionlink",
            constraint=models.UniqueConstraint(
                fields=("pack", "collection"), name="ai_pack_collection_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextresearchnotelink",
            constraint=models.UniqueConstraint(
                fields=("pack", "research_note"), name="ai_pack_research_note_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextresearchsourcelink",
            constraint=models.UniqueConstraint(
                fields=("pack", "research_source"), name="ai_pack_research_source_uniq"
            ),
        ),
    ]
