# Generated by Django 5.2.16 on 2026-07-18 02:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistance", "0004_aicontextartworklink_artwork_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContextManuscriptLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=80)),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("priority", "order", "id"),
                "abstract": False,
            },
        ),
    ]
