# Generated by Django 5.2.16 on 2026-07-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistance", "0005_aicontextmanuscriptlink"),
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicontextmanuscriptlink",
            name="manuscript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_context_links",
                to="publishing.manuscriptproject",
            ),
        ),
        migrations.AddField(
            model_name="aicontextmanuscriptlink",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai_assistance.aicontextpack"
            ),
        ),
        migrations.AddConstraint(
            model_name="aicontextmanuscriptlink",
            constraint=models.UniqueConstraint(
                fields=("pack", "manuscript"), name="ai_pack_manuscript_uniq"
            ),
        ),
    ]
