# Generated by Django 5.2.16 on 2026-07-18 18:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistance", "0007_aicreativerequest_routing_category_and_more"),
        ("decks", "0003_saveddraw_selected_categories_and_more"),
        ("stories", "0003_chapter_editorial_concerns_chapter_final_check_notes_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainstormSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="New Brainstorm", max_length=240)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("plot", "Plot Seeds"),
                            ("realm", "Realm Builder"),
                            ("npc", "NPC Generator"),
                            ("monster", "Monster Generator"),
                            ("item", "Item Generator"),
                        ],
                        default="plot",
                        max_length=16,
                    ),
                ),
                ("focus", models.TextField(blank=True)),
                ("exclusions", models.TextField(blank=True)),
                ("author_notes", models.TextField(blank=True)),
                ("mode_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_sessions",
                        to="stories.chapter",
                    ),
                ),
                (
                    "context_pack",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_session",
                        to="ai_assistance.aicontextpack",
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_sessions",
                        to="decks.saveddraw",
                    ),
                ),
                (
                    "latest_suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_sessions",
                        to="ai_assistance.aicreativesuggestion",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_sessions",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brainstorm_sessions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["workspace", "-updated_at"], name="brainstorm_ws_updated_idx"
                    )
                ],
            },
        ),
    ]
