# Generated by Django 5.2.16 on 2026-07-17 20:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("guidance", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("edition", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="active", max_length=32)),
                ("source_identity", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decks",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="DeckCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_source_identity", models.CharField(max_length=240)),
                ("card_number", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("prompt", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("examples", models.TextField(blank=True)),
                ("back_content", models.TextField(blank=True)),
                ("suit", models.CharField(blank=True, max_length=160)),
                ("mechanical_color", models.CharField(blank=True, max_length=160)),
                ("role", models.CharField(blank=True, max_length=300)),
                ("modifiers", models.JSONField(blank=True, default=list)),
                ("symbols", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("source_file_label", models.CharField(blank=True, max_length=500)),
                ("source_archive_label", models.CharField(blank=True, max_length=500)),
                ("source_page", models.PositiveIntegerField(blank=True, null=True)),
                ("source_position", models.CharField(blank=True, max_length=160)),
                ("source_checksum", models.CharField(blank=True, max_length=64)),
                ("import_checksum", models.CharField(max_length=64)),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_correction", "Needs correction"),
                            ("needs_symbol_review", "Needs symbol review"),
                            ("approved", "Approved"),
                            ("rejected_duplicate", "Rejected as duplicate"),
                            ("intentionally_excluded", "Intentionally excluded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("author_notes", models.TextField(blank=True)),
                ("original_extracted_snapshot", models.JSONField(default=dict)),
                ("has_missing_text", models.BooleanField(default=False)),
                ("has_ambiguous_wording", models.BooleanField(default=False)),
                ("requires_symbol_review", models.BooleanField(default=False)),
                ("is_custom", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "ordering": ("deck__name", "expansion__order", "card_number", "id"),
            },
        ),
        migrations.CreateModel(
            name="DeckCardCue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cue_type", models.CharField(blank=True, max_length=80)),
                ("cue_label", models.CharField(blank=True, max_length=200)),
                ("cue_text", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("symbol", models.CharField(blank=True, max_length=160)),
                ("semantic_label", models.CharField(blank=True, max_length=200)),
                ("meaning", models.TextField(blank=True)),
                ("orientation", models.CharField(blank=True, max_length=80)),
                ("source_provenance", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cues",
                        to="decks.deckcard",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="DeckCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_identity", models.CharField(max_length=240)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="deckcard",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="decks.deckcategory",
            ),
        ),
        migrations.CreateModel(
            name="DeckExpansion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_identity", models.CharField(max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expansions",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="deckcategory",
            name="expansion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="decks.deckexpansion",
            ),
        ),
        migrations.AddField(
            model_name="deckcard",
            name="expansion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="decks.deckexpansion",
            ),
        ),
        migrations.CreateModel(
            name="DeckRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_provenance", models.JSONField(default=dict)),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_correction", "Needs correction"),
                            ("needs_symbol_review", "Needs symbol review"),
                            ("approved", "Approved"),
                            ("rejected_duplicate", "Rejected as duplicate"),
                            ("intentionally_excluded", "Intentionally excluded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stable_source_identity", models.CharField(max_length=240)),
                ("rule_type", models.CharField(blank=True, max_length=120)),
                ("rule_text", models.TextField()),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="decks.deck",
                    ),
                ),
                (
                    "expansion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="decks.deckexpansion",
                    ),
                ),
            ],
            options={
                "ordering": ("deck__name", "expansion__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="FavoriteCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="decks.deckcard",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="favorite_cards",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schema_version", models.PositiveIntegerField()),
                ("source_package_checksum", models.CharField(max_length=64)),
                ("source_collection_label", models.CharField(max_length=500)),
                ("validation_status", models.CharField(max_length=16)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("conflicted_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("report", models.JSONField(default=dict)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deck_import_batches",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_source_identity", models.CharField(max_length=500)),
                ("path_label", models.CharField(max_length=500)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("source_type", models.CharField(max_length=80)),
                ("processing_status", models.CharField(max_length=80)),
                ("report", models.JSONField(default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="decks.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                ("prompt", models.TextField()),
                ("response_type", models.CharField(blank=True, max_length=80)),
                ("order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="decks.journalsection",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="JournalTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("purpose", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("source_identity", models.CharField(max_length=240)),
                ("source_provenance", models.JSONField(default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_correction", "Needs correction"),
                            ("needs_symbol_review", "Needs symbol review"),
                            ("approved", "Approved"),
                            ("rejected_duplicate", "Rejected as duplicate"),
                            ("intentionally_excluded", "Intentionally excluded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journals",
                        to="decks.deck",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_templates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="journalsection",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="decks.journaltemplate",
            ),
        ),
        migrations.CreateModel(
            name="SpreadTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_provenance", models.JSONField(default=dict)),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_correction", "Needs correction"),
                            ("needs_symbol_review", "Needs symbol review"),
                            ("approved", "Approved"),
                            ("rejected_duplicate", "Rejected as duplicate"),
                            ("intentionally_excluded", "Intentionally excluded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stable_source_identity", models.CharField(max_length=240)),
                ("purpose", models.TextField(blank=True)),
                ("instructions", models.TextField()),
                ("minimum_cards", models.PositiveIntegerField(default=0)),
                ("maximum_cards", models.PositiveIntegerField(default=0)),
                ("allows_redraw", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spreads",
                        to="decks.deck",
                    ),
                ),
                (
                    "expansion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spreads",
                        to="decks.deckexpansion",
                    ),
                ),
            ],
            options={
                "ordering": ("deck__name", "expansion__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SpreadPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=300)),
                ("meaning", models.TextField(blank=True)),
                ("required_category_label", models.CharField(blank=True, max_length=160)),
                ("is_optional", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "required_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spread_positions",
                        to="decks.deckcategory",
                    ),
                ),
                (
                    "spread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="decks.spreadtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                fields=("workspace", "source_identity"), name="deck_workspace_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deckcardcue",
            constraint=models.UniqueConstraint(
                fields=("card", "order"), name="cue_card_order_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deckexpansion",
            constraint=models.UniqueConstraint(
                fields=("deck", "source_identity"), name="expansion_deck_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deckcategory",
            constraint=models.UniqueConstraint(
                fields=("deck", "source_identity"), name="category_deck_source_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="deckcard",
            index=models.Index(fields=["deck", "review_status"], name="deck_card_review_idx"),
        ),
        migrations.AddIndex(
            model_name="deckcard",
            index=models.Index(fields=["deck", "extraction_confidence"], name="deck_card_conf_idx"),
        ),
        migrations.AddConstraint(
            model_name="deckcard",
            constraint=models.UniqueConstraint(
                fields=("deck", "stable_source_identity"), name="card_deck_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deckrule",
            constraint=models.UniqueConstraint(
                fields=("deck", "stable_source_identity"), name="rule_deck_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoritecard",
            constraint=models.UniqueConstraint(
                fields=("workspace", "card"), name="favorite_workspace_card_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalprompt",
            constraint=models.UniqueConstraint(
                fields=("section", "order"), name="journal_prompt_order_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="journaltemplate",
            constraint=models.UniqueConstraint(
                fields=("workspace", "source_identity"), name="journal_workspace_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalsection",
            constraint=models.UniqueConstraint(
                fields=("journal", "order"), name="journal_section_order_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadtemplate",
            constraint=models.UniqueConstraint(
                fields=("deck", "stable_source_identity"), name="spread_deck_source_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="spreadposition",
            constraint=models.UniqueConstraint(
                fields=("spread", "order"), name="spread_position_order_uniq"
            ),
        ),
    ]
