# Generated by Django 5.2.16 on 2026-07-17 22:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("decks", "0001_initial"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("workspaces", "0001_initial"),
        ("worldbuilding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawInterpretation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("interpretation_text", models.TextField(blank=True)),
                ("unresolved_questions", models.TextField(blank=True)),
                ("opportunities", models.TextField(blank=True)),
                ("risks_complications", models.TextField(blank=True)),
                ("author_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("accepted", "Accepted"),
                            ("revised", "Revised"),
                            ("rejected", "Rejected"),
                            ("unresolved", "Unresolved"),
                            ("converted", "Converted"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrawCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position_order", models.PositiveIntegerField()),
                ("custom_position_label", models.CharField(blank=True, max_length=240)),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("upright", "Upright"),
                            ("reversed", "Reversed"),
                            ("rotated", "Rotated"),
                        ],
                        default="upright",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("redrawn", "Redrawn"),
                            ("replaced", "Replaced"),
                            ("discarded", "Discarded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("draw_sequence", models.PositiveIntegerField(default=1)),
                ("author_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_occurrences",
                        to="decks.deckcard",
                    ),
                ),
                (
                    "spread_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_cards",
                        to="decks.spreadposition",
                    ),
                ),
            ],
            options={
                "ordering": ("position_order", "draw_sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="DrawDeckSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_selections",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="DrawConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_type", models.CharField(max_length=40)),
                ("action", models.CharField(default="create", max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.chapter",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.character",
                    ),
                ),
                (
                    "codex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.work",
                    ),
                ),
                (
                    "interpretation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions",
                        to="decks.drawinterpretation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedDraw",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                (
                    "draw_mode",
                    models.CharField(
                        choices=[
                            ("official_spread", "Official spread"),
                            ("free_draw", "Free draw"),
                            ("manual_selection", "Manual selection"),
                            ("random_draw", "Random draw"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("interpreted", "Interpreted"),
                            ("converted", "Converted"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("random_seed", models.CharField(blank=True, max_length=120)),
                ("tone_guidance", models.TextField(blank=True)),
                ("genre_guidance", models.TextField(blank=True)),
                ("adult_audience_guidance", models.TextField(blank=True)),
                ("exclusions", models.TextField(blank=True)),
                ("author_brief", models.TextField(blank=True)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                ("context_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("allow_duplicates", models.BooleanField(default=False)),
                ("include_pending", models.BooleanField(default=False)),
                ("include_inactive", models.BooleanField(default=False)),
                (
                    "favorite_mode",
                    models.CharField(
                        choices=[
                            ("all", "All cards"),
                            ("only", "Favorites only"),
                            ("exclude", "Exclude favorites"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deck_draws",
                        to="stories.chapter",
                    ),
                ),
                (
                    "decks",
                    models.ManyToManyField(
                        related_name="draws", through="decks.DrawDeckSelection", to="decks.deck"
                    ),
                ),
                (
                    "primary_deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_draws",
                        to="decks.deck",
                    ),
                ),
                (
                    "spread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draws",
                        to="decks.spreadtemplate",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deck_draws",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_draws",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DrawRegionContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="worldbuilding.region"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawLocationContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="worldbuilding.location"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawItemContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="worldbuilding.worlditem"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="drawinterpretation",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interpretations",
                to="decks.saveddraw",
            ),
        ),
        migrations.CreateModel(
            name="DrawGroupContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="characters.charactergroup"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="drawdeckselection",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deck_selections",
                to="decks.saveddraw",
            ),
        ),
        migrations.CreateModel(
            name="DrawCreatureContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="worldbuilding.creature"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawCodexContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="worldbuilding.codexentry"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawCharacterContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="characters.character"
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decks.saveddraw"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawCardHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("sequence", models.PositiveIntegerField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="decks.drawcard",
                    ),
                ),
                (
                    "previous_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_history_from",
                        to="decks.deckcard",
                    ),
                ),
                (
                    "replacement_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_history_to",
                        to="decks.deckcard",
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_history",
                        to="decks.saveddraw",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="drawcard",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_cards",
                to="decks.saveddraw",
            ),
        ),
        migrations.AddIndex(
            model_name="saveddraw",
            index=models.Index(
                fields=["workspace", "status", "-updated_at"], name="draw_ws_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawregioncontext",
            constraint=models.UniqueConstraint(fields=("draw", "region"), name="draw_region_uniq"),
        ),
        migrations.AddConstraint(
            model_name="drawlocationcontext",
            constraint=models.UniqueConstraint(
                fields=("draw", "location"), name="draw_location_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawitemcontext",
            constraint=models.UniqueConstraint(fields=("draw", "item"), name="draw_item_uniq"),
        ),
        migrations.AddConstraint(
            model_name="drawgroupcontext",
            constraint=models.UniqueConstraint(fields=("draw", "group"), name="draw_group_uniq"),
        ),
        migrations.AddConstraint(
            model_name="drawdeckselection",
            constraint=models.UniqueConstraint(fields=("draw", "deck"), name="draw_deck_uniq"),
        ),
        migrations.AddConstraint(
            model_name="drawcreaturecontext",
            constraint=models.UniqueConstraint(
                fields=("draw", "creature"), name="draw_creature_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawcodexcontext",
            constraint=models.UniqueConstraint(fields=("draw", "codex"), name="draw_codex_uniq"),
        ),
        migrations.AddConstraint(
            model_name="drawcharactercontext",
            constraint=models.UniqueConstraint(
                fields=("draw", "character"), name="draw_character_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawcard",
            constraint=models.UniqueConstraint(
                fields=("draw", "position_order"), name="draw_position_uniq"
            ),
        ),
    ]
