# Generated by Django 5.2.16 on 2026-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decks", "0002_drawinterpretation_drawcard_drawdeckselection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddraw",
            name="selected_categories",
            field=models.ManyToManyField(
                blank=True, related_name="filtered_draws", to="decks.deckcategory"
            ),
        ),
        migrations.AddField(
            model_name="saveddraw",
            name="selected_expansions",
            field=models.ManyToManyField(
                blank=True, related_name="filtered_draws", to="decks.deckexpansion"
            ),
        ),
    ]
