# Generated by Django 5.2.16 on 2026-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_authenticationchallenge_authenticationthrottle_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="authenticationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ("webauthn_register", "webauthn_authenticate"))),
                name="authentication_challenge_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionassurance",
            constraint=models.CheckConstraint(
                condition=models.Q(("assurance_level__in", ("password", "mfa"))),
                name="session_assurance_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("pending", "active", "revoked"))),
                name="totp_credential_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("algorithm", "SHA1"), ("digits", 6), ("period", 30)),
                name="totp_parameters_v1_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="webauthncredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("active", "revoked"))),
                name="webauthn_credential_state_valid",
            ),
        ),
    ]
