# Generated by Django 5.2 on 2026-07-11.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("trashed", "Trashed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("ordering", models.BigIntegerField()),
                ("version", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenes",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={"ordering": ("ordering", "id")},
        ),
        migrations.CreateModel(
            name="MutationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("scene_created", "Scene created"),
                            ("scene_content_revised", "Scene content revised"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("owner", "Owner")], default="owner", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mutation_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mutation_operations",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mutation_operations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="SceneRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("revision_number", models.PositiveBigIntegerField()),
                (
                    "content_format_version",
                    models.CharField(default="plain-text-v1", max_length=32),
                ),
                (
                    "normalization_version",
                    models.CharField(default="plain-text-nfc-lf-v1", max_length=32),
                ),
                (
                    "source",
                    models.CharField(choices=[("owner", "Owner")], default="owner", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "base_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_revisions",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "mutation_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_revision",
                        to="scenes.mutationoperation",
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restoration_revisions",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_revisions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={"ordering": ("scene_id", "revision_number")},
        ),
        migrations.AddField(
            model_name="scene",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="scenes.scenerevision",
            ),
        ),
        migrations.AddIndex(
            model_name="mutationoperation",
            index=models.Index(fields=["workspace", "created_at"], name="mutation_ws_created_idx"),
        ),
        migrations.AddIndex(
            model_name="mutationoperation",
            index=models.Index(fields=["scene", "created_at"], name="mutation_scene_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="mutationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(operation_type__in=("scene_created", "scene_content_revised")),
                name="mutation_operation_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mutationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(source__in=("owner",)),
                name="mutation_operation_source_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="scenerevision",
            index=models.Index(
                fields=["scene", "-revision_number"],
                name="revision_scene_num_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scenerevision",
            index=models.Index(fields=["workspace", "created_at"], name="revision_ws_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.UniqueConstraint(
                fields=("scene", "revision_number"),
                name="unique_revision_number_in_scene",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(revision_number__gte=1),
                name="revision_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(content_format_version="plain-text-v1"),
                name="revision_content_format_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(normalization_version="plain-text-nfc-lf-v1"),
                name="revision_normalization_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(source__in=("owner",)),
                name="revision_source_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(
                fields=["workspace", "lifecycle", "ordering"],
                name="scene_ws_lifecycle_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(title__regex="\\S"),
                name="scene_title_contains_nonspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(lifecycle__in=("active", "archived", "trashed")),
                name="scene_lifecycle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(ordering__gte=0), name="scene_ordering_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(version__gte=0), name="scene_version_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.UniqueConstraint(
                fields=("workspace", "ordering"),
                name="unique_scene_ordering_in_workspace",
            ),
        ),
    ]
