# Generated by Django 5.2.16 on 2026-07-12 00:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneSaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("conflicted", "Conflicted"),
                            ("failed_terminal", "Failed terminal"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "failure_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("optimistic_concurrency", "Optimistic concurrency"),
                            ("invalid_request", "Invalid request"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("result_scene_version", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_save_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successful_save_requests",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="save_requests",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_save_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "scene", "created_at"], name="scene_save_ws_scene_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "account", "scene", "idempotency_key"),
                        name="unique_scene_save_request_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ("pending", "succeeded", "conflicted", "failed_terminal"))
                        ),
                        name="scene_save_request_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "failure_classification__in",
                                ("", "optimistic_concurrency", "invalid_request"),
                            )
                        ),
                        name="scene_save_failure_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result_scene_version__isnull", True),
                            ("result_scene_version__gte", 0),
                            _connector="OR",
                        ),
                        name="scene_save_result_version_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scenesaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[A-Za-z0-9._~-]{16,128}$")),
                name="scene_save_key_format_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenesaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="scene_save_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenesaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failure_classification", ""),
                        ("result_revision__isnull", True),
                        ("result_scene_version__isnull", True),
                        ("state", "pending"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_classification", ""),
                        ("result_revision__isnull", False),
                        ("result_scene_version__isnull", False),
                        ("state", "succeeded"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_classification", "optimistic_concurrency"),
                        ("result_revision__isnull", True),
                        ("result_scene_version__isnull", True),
                        ("state", "conflicted"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_classification", "invalid_request"),
                        ("result_revision__isnull", True),
                        ("result_scene_version__isnull", True),
                        ("state", "failed_terminal"),
                    ),
                    _connector="OR",
                ),
                name="scene_save_outcome_consistent",
            ),
        ),
    ]
