# Generated by Django 5.2.16 on 2026-07-12 01:31

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0002_scenesaverequest"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneSearchProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_scene_version", models.BigIntegerField()),
                ("projection_schema_version", models.CharField(max_length=32)),
                ("search_configuration_version", models.CharField(max_length=32)),
                ("title_vector", django.contrib.postgres.search.SearchVectorField()),
                ("body_vector", django.contrib.postgres.search.SearchVectorField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("built_at", models.DateTimeField()),
                (
                    "scene",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_projection",
                        to="scenes.scene",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_projections",
                        to="scenes.scenerevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_search_projections",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title_vector", "body_vector"], name="scene_search_vector_gin"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source_scene_version__gte", 1)),
                        name="search_projection_scene_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("projection_schema_version", "scene-search-v1")),
                        name="search_projection_schema_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("search_configuration_version", "simple-v1")),
                        name="search_configuration_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_content_hash__regex", "^[0-9a-f]{64}$")),
                        name="search_projection_hash_valid",
                    ),
                ],
            },
        ),
    ]
