# Generated by Django 5.2.16 on 2026-07-12 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0003_scenesearchprojection"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mutationoperation",
            name="mutation_operation_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="mutationoperation",
            name="mutation_operation_source_valid",
        ),
        migrations.RemoveConstraint(
            model_name="scenerevision",
            name="revision_source_valid",
        ),
        migrations.AlterField(
            model_name="mutationoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("scene_created", "Scene created"),
                    ("scene_content_revised", "Scene content revised"),
                    ("scene_imported", "Scene imported"),
                    ("scene_revision_imported", "Scene revision imported"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="mutationoperation",
            name="source",
            field=models.CharField(
                choices=[("owner", "Owner"), ("import", "Import")], default="owner", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="scenerevision",
            name="source",
            field=models.CharField(
                choices=[("owner", "Owner"), ("import", "Import")], default="owner", max_length=16
            ),
        ),
        migrations.AddConstraint(
            model_name="mutationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "operation_type__in",
                        (
                            "scene_created",
                            "scene_content_revised",
                            "scene_imported",
                            "scene_revision_imported",
                        ),
                    )
                ),
                name="mutation_operation_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mutationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("owner", "import"))),
                name="mutation_operation_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("owner", "import"))),
                name="revision_source_valid",
            ),
        ),
    ]
