# Generated by Django 5.2.16 on 2026-07-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0004_remove_mutationoperation_mutation_operation_type_valid_and_more"),
        ("stories", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="arc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenes",
                to="stories.arc",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenes",
                to="stories.chapter",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="structure_order",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scene",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenes",
                to="stories.volume",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenes",
                to="stories.work",
            ),
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(
                fields=["workspace", "work", "chapter", "structure_order"],
                name="scene_ws_structure_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("structure_order__isnull", True), ("work__isnull", True)),
                    models.Q(("structure_order__isnull", False), ("work__isnull", False)),
                    _connector="OR",
                ),
                name="scene_placement_order_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("work__isnull", False),
                    models.Q(
                        ("arc__isnull", True), ("chapter__isnull", True), ("volume__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="scene_structure_requires_work",
            ),
        ),
    ]
