# Generated by Django 5.2.16 on 2026-07-13 18:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0004_remove_mutationoperation_mutation_operation_type_valid_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("appearance", models.TextField(blank=True)),
                ("personality", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
                ("internal_conflict", models.TextField(blank=True)),
                ("external_conflict", models.TextField(blank=True)),
                ("voice_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characters",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharacterScene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_links",
                        to="characters.character",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_scene_links",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("scene__ordering", "character__name", "id"),
            },
        ),
        migrations.AddField(
            model_name="character",
            name="scenes",
            field=models.ManyToManyField(
                related_name="characters", through="characters.CharacterScene", to="scenes.scene"
            ),
        ),
        migrations.AddIndex(
            model_name="characterscene",
            index=models.Index(fields=["workspace", "character"], name="char_scene_ws_char_idx"),
        ),
        migrations.AddIndex(
            model_name="characterscene",
            index=models.Index(fields=["workspace", "scene"], name="char_scene_ws_scene_idx"),
        ),
        migrations.AddConstraint(
            model_name="characterscene",
            constraint=models.UniqueConstraint(
                fields=("character", "scene"), name="unique_character_scene_link"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["workspace", "name"], name="character_ws_name_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["workspace", "-updated_at"], name="character_ws_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")), name="character_name_contains_nonspace"
            ),
        ),
    ]
