# Generated by Django 5.2.16 on 2026-07-13 20:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
        ("scenes", "0004_remove_mutationoperation_mutation_operation_type_valid_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("costs", models.TextField(blank=True)),
                (
                    "mastery",
                    models.CharField(
                        choices=[
                            ("latent", "Latent"),
                            ("emerging", "Emerging"),
                            ("trained", "Trained"),
                            ("advanced", "Advanced"),
                            ("mastered", "Mastered"),
                        ],
                        default="emerging",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("lost", "Lost"),
                            ("unstable", "Unstable"),
                            ("sealed", "Sealed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abilities",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abilities",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="AbilityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("story_time", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("awakening", "Awakening"),
                            ("training", "Training"),
                            ("breakthrough", "Breakthrough"),
                            ("failure", "Failure"),
                            ("injury", "Injury"),
                            ("loss", "Loss"),
                            ("discovery", "Discovery"),
                            ("transformation", "Transformation"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="characters.ability",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ability_events",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ability_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AbilityPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("prediction", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("came_true", "Came true"),
                            ("diverged", "Diverged"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="characters.ability",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ability_predictions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AbilityStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("past", "Past"),
                            ("current", "Current"),
                            ("possible", "Possible"),
                            ("rejected", "Rejected"),
                        ],
                        default="possible",
                        max_length=16,
                    ),
                ),
                ("requirements", models.TextField(blank=True)),
                ("costs", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="characters.ability",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ability_stages",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="ability",
            index=models.Index(fields=["workspace", "character"], name="ability_ws_character_idx"),
        ),
        migrations.AddIndex(
            model_name="ability",
            index=models.Index(fields=["workspace", "-updated_at"], name="ability_ws_updated_idx"),
        ),
        migrations.AddConstraint(
            model_name="ability",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")), name="ability_name_contains_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="ability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mastery__in", ("latent", "emerging", "trained", "advanced", "mastered"))
                ),
                name="ability_mastery_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("active", "dormant", "lost", "unstable", "sealed"))
                ),
                name="ability_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="abilityevent",
            index=models.Index(fields=["workspace", "ability"], name="event_ws_ability_idx"),
        ),
        migrations.AddIndex(
            model_name="abilityevent",
            index=models.Index(fields=["workspace", "-created_at"], name="event_ws_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="abilityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")), name="ability_event_title_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="abilityevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        (
                            "awakening",
                            "training",
                            "breakthrough",
                            "failure",
                            "injury",
                            "loss",
                            "discovery",
                            "transformation",
                        ),
                    )
                ),
                name="ability_event_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="abilityprediction",
            index=models.Index(fields=["workspace", "ability"], name="prediction_ws_ability_idx"),
        ),
        migrations.AddConstraint(
            model_name="abilityprediction",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "\\S")),
                name="ability_prediction_title_nonspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="abilityprediction",
            constraint=models.CheckConstraint(
                condition=models.Q(("prediction__regex", "\\S")), name="ability_prediction_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="abilityprediction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("active", "came_true", "diverged", "dismissed"))
                ),
                name="ability_prediction_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="abilitystage",
            index=models.Index(fields=["workspace", "ability"], name="stage_ws_ability_idx"),
        ),
        migrations.AddConstraint(
            model_name="abilitystage",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")), name="ability_stage_name_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="abilitystage",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("past", "current", "possible", "rejected"))),
                name="ability_stage_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="abilitystage",
            constraint=models.UniqueConstraint(
                fields=("ability", "order"), name="unique_ability_stage_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="abilitystage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "current")),
                fields=("ability",),
                name="unique_current_stage_per_ability",
            ),
        ),
    ]
