# Generated by Django 5.2.16 on 2026-07-13 21:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_ability_abilityevent_abilityprediction_abilitystage_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("team", "Team"),
                            ("faction", "Faction"),
                            ("organization", "Organization"),
                            ("crew", "Crew"),
                            ("household", "Household"),
                            ("order", "Order"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("dissolved", "Dissolved"),
                            ("historical", "Historical"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_groups",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("ally", "Ally"),
                            ("friend", "Friend"),
                            ("rival", "Rival"),
                            ("enemy", "Enemy"),
                            ("romantic", "Romantic"),
                            ("mentor", "Mentor"),
                            ("student", "Student"),
                            ("employer", "Employer"),
                            ("subordinate", "Subordinate"),
                            ("professional", "Professional"),
                            ("dependent", "Dependent"),
                            ("complicated", "Complicated"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("short_label", models.CharField(blank=True, max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("source_perspective", models.TextField(blank=True)),
                ("target_perspective", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("strained", "Strained"),
                            ("broken", "Broken"),
                            ("hidden", "Hidden"),
                            ("resolved", "Resolved"),
                            ("historical", "Historical"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "knowledge_state",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("secret", "Secret"),
                            ("one_sided", "One-sided"),
                            ("unknown", "Unknown"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_source",
                        to="characters.character",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_target",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_relationships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("former", "Former"),
                            ("hidden", "Hidden"),
                            ("honorary", "Honorary"),
                            ("deceased", "Deceased"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("rank_label", models.CharField(blank=True, max_length=120)),
                ("joined_story_time", models.CharField(blank=True, max_length=120)),
                ("left_story_time", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="characters.character",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("character__name", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="charactergroup",
            index=models.Index(fields=["workspace", "name"], name="character_group_ws_name_idx"),
        ),
        migrations.AddIndex(
            model_name="charactergroup",
            index=models.Index(
                fields=["workspace", "-updated_at"], name="character_group_ws_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="charactergroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "\\S")), name="character_group_name_nonspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="charactergroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "group_type__in",
                        (
                            "family",
                            "team",
                            "faction",
                            "organization",
                            "crew",
                            "household",
                            "order",
                            "other",
                        ),
                    )
                ),
                name="character_group_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactergroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("active", "inactive", "dissolved", "historical"))
                ),
                name="character_group_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="characterrelationship",
            index=models.Index(fields=["workspace", "source"], name="relationship_ws_source_idx"),
        ),
        migrations.AddIndex(
            model_name="characterrelationship",
            index=models.Index(fields=["workspace", "target"], name="relationship_ws_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_id__lt", models.F("target_id"))),
                name="relationship_pair_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "relationship_type__in",
                        (
                            "family",
                            "ally",
                            "friend",
                            "rival",
                            "enemy",
                            "romantic",
                            "mentor",
                            "student",
                            "employer",
                            "subordinate",
                            "professional",
                            "dependent",
                            "complicated",
                            "other",
                        ),
                    )
                ),
                name="relationship_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("active", "strained", "broken", "hidden", "resolved", "historical"),
                    )
                ),
                name="relationship_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("knowledge_state__in", ("public", "private", "secret", "one_sided", "unknown"))
                ),
                name="relationship_knowledge_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.UniqueConstraint(
                fields=("source", "target"), name="unique_character_relationship_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(fields=["workspace", "character"], name="membership_ws_char_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(fields=["workspace", "group"], name="membership_ws_group_idx"),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("active", "former", "hidden", "honorary", "deceased", "unknown"),
                    )
                ),
                name="group_membership_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("character", "group"), name="unique_character_group_membership"
            ),
        ),
    ]
