# Generated by Django 5.2.16 on 2026-07-17 15:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_charactergroup_characterrelationship_groupmembership_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactergroup",
            name="alignment",
            field=models.CharField(
                choices=[
                    ("allied", "Allied"),
                    ("friendly", "Friendly"),
                    ("neutral", "Neutral"),
                    ("hostile", "Hostile"),
                    ("mixed", "Mixed"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="allies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="current_conflicts",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="enemies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="hidden_goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="leadership_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="methods",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="public_goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="reputation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="resources",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactergroup",
            name="territory",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="GroupRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("allied", "Allied"),
                            ("hostile", "Hostile"),
                            ("subordinate", "Subordinate"),
                            ("rival", "Rival"),
                            ("trading_partner", "Trading partner"),
                            ("ceasefire", "Ceasefire"),
                            ("secret_collaboration", "Secret collaboration"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("source_perspective", models.TextField(blank=True)),
                ("target_perspective", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_source",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_target",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_relationships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source_id__lt", models.F("target_id"))),
                        name="group_rel_pair_order",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "target"), name="unique_group_rel_pair"
                    ),
                ],
            },
        ),
    ]
