# Generated by Django 5.2.16 on 2026-07-18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more")]

    operations = [
        migrations.CreateModel(
            name="CharacterPersonalityTrait",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("score", models.SmallIntegerField(default=0)),
                ("low_label", models.CharField(blank=True, max_length=80)),
                ("high_label", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personality_traits",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_personality_traits",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name", "id"),
                "indexes": [
                    models.Index(
                        fields=["workspace", "character"], name="personality_ws_character_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", -5), ("score__lte", 5)),
                        name="personality_trait_score_range",
                    ),
                    models.UniqueConstraint(
                        fields=("character", "name"),
                        name="unique_character_personality_trait",
                    ),
                ],
            },
        )
    ]
