# Generated by Django 5.2.16 on 2026-07-17 22:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("decks", "0003_saveddraw_selected_categories_and_more"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("workspaces", "0001_initial"),
        ("worldbuilding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                (
                    "thread_type",
                    models.CharField(
                        choices=[
                            ("foreshadowing", "Foreshadowing"),
                            ("mystery", "Mystery"),
                            ("promise", "Promise"),
                            ("threat", "Threat"),
                            ("callback", "Callback"),
                            ("motif", "Motif"),
                            ("character_arc", "Character Arc"),
                            ("relationship_arc", "Relationship Arc"),
                            ("world_arc", "World Arc"),
                            ("political_arc", "Political Arc"),
                            ("object_arc", "Object Arc"),
                            ("location_arc", "Location Arc"),
                            ("prophecy", "Prophecy"),
                            ("question", "Question"),
                            ("setup", "Setup"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("open", "Open"),
                            ("developing", "Developing"),
                            ("dormant", "Dormant"),
                            ("endangered", "Endangered"),
                            ("resolved", "Resolved"),
                            ("abandoned", "Abandoned"),
                            ("superseded", "Superseded"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("background", "Background"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("author_only", "Author Only"),
                            ("reader_aware", "Reader Aware"),
                            ("character_aware", "Character Aware"),
                            ("public_world", "Public World"),
                            ("hidden", "Hidden"),
                            ("disputed", "Disputed"),
                        ],
                        default="author_only",
                        max_length=24,
                    ),
                ),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("watch", "Watch"),
                            ("endangered", "Endangered"),
                            ("blocked", "Blocked"),
                            ("resolved", "Resolved"),
                        ],
                        default="healthy",
                        max_length=16,
                    ),
                ),
                ("short_summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("intended_payoff", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("introduced_story_time", models.CharField(blank=True, max_length=160)),
                ("target_resolution_story_time", models.CharField(blank=True, max_length=160)),
                ("resolved_story_time", models.CharField(blank=True, max_length=160)),
                ("next_action", models.TextField(blank=True)),
                ("next_review_label", models.CharField(blank=True, max_length=160)),
                ("blocker_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plot_threads",
                        to="stories.arc",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plot_threads",
                        to="stories.volume",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plot_threads",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plot_threads",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("secret_type", models.CharField(default="other", max_length=32)),
                ("status", models.CharField(default="hidden", max_length=24)),
                ("truth_statement", models.TextField()),
                ("public_belief", models.TextField(blank=True)),
                ("why_it_matters", models.TextField(blank=True)),
                ("consequences_if_revealed", models.TextField(blank=True)),
                ("intended_reveal", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secrets",
                        to="continuity.plotthread",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secrets",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secrets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReaderKnowledgeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subject_type", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=240)),
                ("knowledge_statement", models.TextField()),
                ("certainty", models.CharField(default="ambiguous", max_length=24)),
                ("status", models.CharField(default="current", max_length=32)),
                ("learned_story_time", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.chapter",
                    ),
                ),
                (
                    "character_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="characters.character",
                    ),
                ),
                (
                    "codex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "group_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scenes.scene",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="continuity.plotthread",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reader_knowledge",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="continuity.secret",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterKnowledgeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("knowledge_statement", models.TextField()),
                ("knowledge_state", models.CharField(default="knows", max_length=24)),
                ("certainty", models.CharField(default="uncertain", max_length=24)),
                ("source", models.TextField(blank=True)),
                ("learned_story_time", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.chapter",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_records",
                        to="characters.character",
                    ),
                ),
                (
                    "character_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="characters.character",
                    ),
                ),
                (
                    "codex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "group_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scenes.scene",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_knowledge",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="continuity.plotthread",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="continuity.secret",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadChapterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="stories.chapter",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="characters.character",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadClue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("clue_type", models.CharField(default="direct_clue", max_length=32)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("status", models.CharField(default="planned", max_length=20)),
                ("subtlety", models.CharField(default="subtle", max_length=20)),
                ("intended_interpretation", models.TextField(blank=True)),
                ("reader_interpretation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_clues",
                        to="stories.chapter",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_clues",
                        to="scenes.scene",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues",
                        to="continuity.plotthread",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadCreatureLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadDrawLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="decks.saveddraw",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadInterpretationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interpretation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="decks.drawinterpretation",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadProgressEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(default="other", max_length=32)),
                ("title", models.CharField(max_length=240)),
                ("story_time_label", models.CharField(blank=True, max_length=160)),
                ("calendar_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("status_impact", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.chapter",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scenes.scene",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="continuity.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ThreadRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadReveal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("reveal_type", models.CharField(default="partial", max_length=32)),
                ("description", models.TextField()),
                ("status", models.CharField(default="planned", max_length=20)),
                ("target_audience", models.CharField(blank=True, max_length=240)),
                ("consequences", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_reveals",
                        to="stories.chapter",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_reveals",
                        to="scenes.scene",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reveals",
                        to="continuity.plotthread",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadSceneLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.plotthread"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="plotthread",
            index=models.Index(
                fields=["workspace", "status", "priority"], name="thread_ws_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterknowledgerecord",
            constraint=models.UniqueConstraint(
                fields=("character", "secret", "thread", "learned_story_time"),
                name="character_subject_time_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadchapterlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "chapter"), name="thread_chapter_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadcharacterlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "character"), name="thread_character_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadcodexlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "codex"), name="thread_codex_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadcreaturelink",
            constraint=models.UniqueConstraint(
                fields=("thread", "creature"), name="thread_creature_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threaddrawlink",
            constraint=models.UniqueConstraint(fields=("thread", "draw"), name="thread_draw_uniq"),
        ),
        migrations.AddConstraint(
            model_name="threadgrouplink",
            constraint=models.UniqueConstraint(
                fields=("thread", "group"), name="thread_group_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadinterpretationlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "interpretation"), name="thread_interp_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threaditemlink",
            constraint=models.UniqueConstraint(fields=("thread", "item"), name="thread_item_uniq"),
        ),
        migrations.AddConstraint(
            model_name="threadlocationlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "location"), name="thread_location_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadregionlink",
            constraint=models.UniqueConstraint(
                fields=("thread", "region"), name="thread_region_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadscenelink",
            constraint=models.UniqueConstraint(
                fields=("thread", "scene"), name="thread_scene_uniq"
            ),
        ),
    ]
