# Generated by Django 5.2.16 on 2026-07-17 22:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("continuity", "0001_initial"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("worldbuilding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretChapterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="stories.chapter",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "chapter"), name="secret_chapter_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="characters.character",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "character"), name="secret_character_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("secret", "codex"), name="secret_codex_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretCreatureLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "creature"), name="secret_creature_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("secret", "group"), name="secret_group_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("secret", "item"), name="secret_item_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "location"), name="secret_location_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("secret", "region"), name="secret_region_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretSceneLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="subject", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="continuity.secret"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("secret", "scene"), name="secret_scene_uniq")
                ],
            },
        ),
    ]
