# Generated by Django 5.2.16 on 2026-07-17 23:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("continuity", "0002_secretchapterlink_secretcharacterlink_and_more"),
        ("decks", "0003_saveddraw_selected_categories_and_more"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("workspaces", "0001_initial"),
        ("worldbuilding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                (
                    "timeline_type",
                    models.CharField(
                        choices=[
                            ("primary_story", "Primary Story"),
                            ("historical", "Historical"),
                            ("character", "Character"),
                            ("faction", "Faction"),
                            ("location", "Location"),
                            ("ability_progression", "Ability Progression"),
                            ("publication", "Publication"),
                            ("alternate", "Alternate"),
                            ("prophecy", "Prophecy"),
                            ("other", "Other"),
                        ],
                        default="primary_story",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("calendar_system_label", models.CharField(blank=True, max_length=160)),
                ("epoch_notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timelines",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timelines",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("story_event", "Story Event"),
                            ("historical_event", "Historical Event"),
                            ("birth", "Birth"),
                            ("death", "Death"),
                            ("disappearance", "Disappearance"),
                            ("discovery", "Discovery"),
                            ("battle", "Battle"),
                            ("journey", "Journey"),
                            ("political_event", "Political Event"),
                            ("relationship_event", "Relationship Event"),
                            ("ability_event", "Ability Event"),
                            ("revelation", "Revelation"),
                            ("secret_exposed", "Secret Exposed"),
                            ("clue_planted", "Clue Planted"),
                            ("plot_thread_event", "Plot Thread Event"),
                            ("location_event", "Location Event"),
                            ("item_event", "Item Event"),
                            ("creature_event", "Creature Event"),
                            ("cultural_event", "Cultural Event"),
                            ("prophecy", "Prophecy"),
                            ("publication_event", "Publication Event"),
                            ("other", "Other"),
                        ],
                        default="story_event",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("established", "Established"),
                            ("disputed", "Disputed"),
                            ("speculative", "Speculative"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("short_summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "chronology_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("approximate", "Approximate"),
                            ("range", "Range"),
                            ("relative", "Relative"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "start_sort_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "end_sort_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("display_date", models.CharField(blank=True, max_length=200)),
                ("end_label", models.CharField(blank=True, max_length=200)),
                ("era_label", models.CharField(blank=True, max_length=160)),
                ("uncertainty_notes", models.TextField(blank=True)),
                (
                    "significance",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("supporting", "Supporting"),
                            ("minor", "Minor"),
                            ("background", "Background"),
                        ],
                        default="supporting",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("author_only", "Author Only"),
                            ("reader_known", "Reader Known"),
                            ("character_known", "Character Known"),
                            ("public_world", "Public World"),
                            ("secret", "Secret"),
                            ("disputed", "Disputed"),
                        ],
                        default="author_only",
                        max_length=24,
                    ),
                ),
                ("consequences", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="timeline.timeline",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_events",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": (
                    models.OrderBy(models.F("start_sort_value"), nulls_last=True),
                    "display_date",
                    "id",
                ),
            },
        ),
        migrations.CreateModel(
            name="EventWorkLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_event_links",
                        to="stories.work",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventVolumeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="stories.volume",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventThreadLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.plotthread",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventSecretLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.secret",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventSceneLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventRevealLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reveal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.threadreveal",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventRelationshipLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.characterrelationship",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventReaderKnowledgeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.readerknowledgerecord",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventInterpretationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interpretation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="decks.drawinterpretation",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventDrawLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="decks.saveddraw",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCreatureLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventClueLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.threadclue",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.character",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCharacterKnowledgeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="continuity.characterknowledgerecord",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventChapterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="stories.chapter",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventArcLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="stories.arc",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventAbilityStageLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.abilitystage",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventAbilityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.ability",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventAbilityEventLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="other", max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ability_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_links",
                        to="characters.abilityevent",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="timeline.timelineevent"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimelineEventRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("simultaneous", "Simultaneous"),
                            ("overlaps", "Overlaps"),
                            ("causes", "Causes"),
                            ("enables", "Enables"),
                            ("prevents", "Prevents"),
                            ("contradicts", "Contradicts"),
                            ("retells", "Retells"),
                            ("flashback_to", "Flashback To"),
                            ("prophecy_of", "Prophecy Of"),
                            ("alternate_version", "Alternate Version"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="high",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="timeline.timelineevent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="timeline.timelineevent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="timeline",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="timeline_ws_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["workspace", "timeline", "start_sort_value"], name="event_ws_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventworklink",
            constraint=models.UniqueConstraint(fields=("event", "work"), name="event_work_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventvolumelink",
            constraint=models.UniqueConstraint(
                fields=("event", "volume"), name="event_volume_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventthreadlink",
            constraint=models.UniqueConstraint(
                fields=("event", "thread"), name="event_thread_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsecretlink",
            constraint=models.UniqueConstraint(
                fields=("event", "secret"), name="event_secret_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventscenelink",
            constraint=models.UniqueConstraint(fields=("event", "scene"), name="event_scene_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventreveallink",
            constraint=models.UniqueConstraint(
                fields=("event", "reveal"), name="event_reveal_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrelationshiplink",
            constraint=models.UniqueConstraint(
                fields=("event", "relationship"), name="event_relationship_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventregionlink",
            constraint=models.UniqueConstraint(
                fields=("event", "region"), name="event_region_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventreaderknowledgelink",
            constraint=models.UniqueConstraint(
                fields=("event", "knowledge"), name="event_reader_knowledge_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventlocationlink",
            constraint=models.UniqueConstraint(
                fields=("event", "location"), name="event_location_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitemlink",
            constraint=models.UniqueConstraint(fields=("event", "item"), name="event_item_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventinterpretationlink",
            constraint=models.UniqueConstraint(
                fields=("event", "interpretation"), name="event_interpretation_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventgrouplink",
            constraint=models.UniqueConstraint(fields=("event", "group"), name="event_group_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventdrawlink",
            constraint=models.UniqueConstraint(fields=("event", "draw"), name="event_draw_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventcreaturelink",
            constraint=models.UniqueConstraint(
                fields=("event", "creature"), name="event_creature_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcodexlink",
            constraint=models.UniqueConstraint(fields=("event", "codex"), name="event_codex_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventcluelink",
            constraint=models.UniqueConstraint(fields=("event", "clue"), name="event_clue_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventcharacterlink",
            constraint=models.UniqueConstraint(
                fields=("event", "character"), name="event_character_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcharacterknowledgelink",
            constraint=models.UniqueConstraint(
                fields=("event", "knowledge"), name="event_character_knowledge_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventchapterlink",
            constraint=models.UniqueConstraint(
                fields=("event", "chapter"), name="event_chapter_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventarclink",
            constraint=models.UniqueConstraint(fields=("event", "arc"), name="event_arc_uniq"),
        ),
        migrations.AddConstraint(
            model_name="eventabilitystagelink",
            constraint=models.UniqueConstraint(
                fields=("event", "stage"), name="event_ability_stage_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventabilitylink",
            constraint=models.UniqueConstraint(
                fields=("event", "ability"), name="event_ability_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventabilityeventlink",
            constraint=models.UniqueConstraint(
                fields=("event", "ability_event"), name="event_ability_event_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineeventrelation",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relation_type"), name="event_relation_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineeventrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="event_relation_not_self",
            ),
        ),
    ]
