# Generated by Django 5.2.16 on 2026-07-17 15:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0004_charactergroup_alignment_charactergroup_allies_and_more"),
        ("scenes", "0005_scene_arc_scene_chapter_scene_structure_order_and_more"),
        ("stories", "0002_chapter_brain_dump_chapter_character_focus_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodexEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("term", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("history", "History"),
                            ("biology", "Biology"),
                            ("culture", "Culture"),
                            ("technology", "Technology"),
                            ("magic", "Magic or power system"),
                            ("language", "Language"),
                            ("law", "Law"),
                            ("religion", "Religion or belief"),
                            ("custom", "Custom"),
                            ("event", "Event"),
                            ("terminology", "Terminology"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=120)),
                ("definition", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("implications", models.TextField(blank=True)),
                ("related_terms", models.TextField(blank=True)),
                (
                    "canon_state",
                    models.CharField(
                        choices=[
                            ("canon", "Canon"),
                            ("draft", "Draft"),
                            ("speculative", "Speculative"),
                            ("disputed", "Disputed"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("provenance_note", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codex_entries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("term", "id"),
            },
        ),
        migrations.CreateModel(
            name="Creature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creature_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("species", "Species"),
                            ("monster", "Monster"),
                            ("animal", "Animal"),
                            ("construct", "Construct"),
                            ("spirit", "Spirit"),
                            ("entity", "Entity"),
                            ("engineered", "Engineered organism"),
                            ("alien", "Alien"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("classification", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("extinct", "Extinct"),
                            ("dormant", "Dormant"),
                            ("imprisoned", "Imprisoned"),
                            ("missing", "Missing"),
                            ("destroyed", "Destroyed"),
                            ("unknown", "Unknown"),
                            ("legendary", "Legendary"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("negligible", "Negligible"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("severe", "Severe"),
                            ("catastrophic", "Catastrophic"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("intelligence", models.CharField(blank=True, max_length=120)),
                ("appearance", models.TextField(blank=True)),
                ("biology", models.TextField(blank=True)),
                ("habitat", models.TextField(blank=True)),
                ("behavior", models.TextField(blank=True)),
                ("diet", models.TextField(blank=True)),
                ("abilities", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("signs", models.TextField(blank=True)),
                ("ecology", models.TextField(blank=True)),
                ("origin", models.TextField(blank=True)),
                ("cultural_significance", models.TextField(blank=True)),
                ("encounter_notes", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creatures",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("continent", "Continent"),
                            ("country", "Country"),
                            ("territory", "Territory"),
                            ("province", "Province"),
                            ("zone", "Zone"),
                            ("district", "District"),
                            ("realm", "Realm"),
                            ("planet", "Planet"),
                            ("system", "System"),
                            ("dimension", "Dimension"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("known", "Known"),
                            ("unknown", "Unknown"),
                            ("contested", "Contested"),
                            ("occupied", "Occupied"),
                            ("destroyed", "Destroyed"),
                            ("inaccessible", "Inaccessible"),
                            ("historical", "Historical"),
                        ],
                        default="known",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("geography", models.TextField(blank=True)),
                ("climate", models.TextField(blank=True)),
                ("cultures", models.TextField(blank=True)),
                ("government", models.TextField(blank=True)),
                ("notable_features", models.TextField(blank=True)),
                ("hazards", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("settlement", "Settlement"),
                            ("building", "Building"),
                            ("landmark", "Landmark"),
                            ("wilderness", "Wilderness"),
                            ("realm", "Realm"),
                            ("planet", "Planet"),
                            ("station", "Station"),
                            ("vessel", "Vessel"),
                            ("battlefield", "Battlefield"),
                            ("interior", "Interior"),
                            ("abstract", "Abstract space"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("abandoned", "Abandoned"),
                            ("ruins", "Ruins"),
                            ("destroyed", "Destroyed"),
                            ("hidden", "Hidden"),
                            ("inaccessible", "Inaccessible"),
                            ("unknown", "Unknown"),
                            ("historical", "Historical"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("history", models.TextField(blank=True)),
                ("current_state", models.TextField(blank=True)),
                ("atmosphere", models.TextField(blank=True)),
                ("notable_features", models.TextField(blank=True)),
                ("sensory_notes", models.TextField(blank=True)),
                ("hazards", models.TextField(blank=True)),
                ("culture", models.TextField(blank=True)),
                ("travel_notes", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="worldbuilding.region",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorldItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("aliases", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("artifact", "Artifact"),
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("tool", "Tool"),
                            ("technology", "Technology"),
                            ("vehicle", "Vehicle"),
                            ("vessel", "Vessel"),
                            ("document", "Document"),
                            ("relic", "Relic"),
                            ("substance", "Substance"),
                            ("device", "Device"),
                            ("key_item", "Key item"),
                            ("ordinary", "Ordinary object"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lost", "Lost"),
                            ("destroyed", "Destroyed"),
                            ("damaged", "Damaged"),
                            ("hidden", "Hidden"),
                            ("sealed", "Sealed"),
                            ("unknown", "Unknown"),
                            ("historical", "Historical"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("significance", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("appearance", models.TextField(blank=True)),
                ("origin", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("capabilities", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("costs_dangers", models.TextField(blank=True)),
                ("current_condition", models.TextField(blank=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_items",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="world_items",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodexCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexcharacterlink_links",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexcharacterlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "character"), name="unique_codexcharacterlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexChapterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexchapterlink_links",
                        to="stories.chapter",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexchapterlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "chapter"), name="unique_codexchapterlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexgrouplink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexgrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "group"), name="unique_codexgrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relations_as_source",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relations_as_target",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codex_relations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source_id__lt", models.F("target_id"))),
                        name="codex_rel_pair_order",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "target"), name="unique_codex_rel_pair"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexWorkLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexworklink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexworklink_links",
                        to="stories.work",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "work"), name="unique_codexworklink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatureCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturecharacterlink_links",
                        to="characters.character",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturecharacterlink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "character"), name="unique_creaturecharacterlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatureCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturecodexlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturecodexlink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "codex"), name="unique_creaturecodexlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatureGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturegrouplink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturegrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "group"), name="unique_creaturegrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatureLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturelocationlink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creaturelocationlink_links",
                        to="worldbuilding.location",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "location"), name="unique_creaturelocationlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexlocationlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexlocationlink_links",
                        to="worldbuilding.location",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "location"), name="unique_codexlocationlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locationcharacterlink_links",
                        to="characters.character",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locationcharacterlink_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "character"), name="unique_locationcharacterlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locationgrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locationgrouplink_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "group"), name="unique_locationgrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreatureRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creatureregionlink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creatureregionlink_links",
                        to="worldbuilding.region",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "region"), name="unique_creatureregionlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexregionlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexregionlink_links",
                        to="worldbuilding.region",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "region"), name="unique_codexregionlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regiongrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regiongrouplink_links",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "group"), name="unique_regiongrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneCodexLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenecodexlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenecodexlink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "codex"), name="unique_scenecodexlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneCreatureLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenecreaturelink_links",
                        to="worldbuilding.creature",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenecreaturelink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "creature"), name="unique_scenecreaturelink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenegrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenegrouplink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "group"), name="unique_scenegrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneLocationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenelocationlink_links",
                        to="worldbuilding.location",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenelocationlink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "location"), name="unique_scenelocationlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneRegionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sceneregionlink_links",
                        to="worldbuilding.region",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sceneregionlink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "region"), name="unique_sceneregionlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SceneItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sceneitemlink_links",
                        to="scenes.scene",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sceneitemlink_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "item"), name="unique_sceneitemlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemGroupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itemgrouplink_links",
                        to="characters.charactergroup",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itemgrouplink_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "group"), name="unique_itemgrouplink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemCharacterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itemcharacterlink_links",
                        to="characters.character",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itemcharacterlink_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "character"), name="unique_itemcharacterlink_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "codex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexitemlink_links",
                        to="worldbuilding.codexentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workspaces.workspace"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codexitemlink_links",
                        to="worldbuilding.worlditem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex", "item"), name="unique_codexitemlink_pair"
                    )
                ],
            },
        ),
    ]
