# Generated by Django 5.2.16 on 2026-07-12 01:22

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "job_type",
                    models.CharField(choices=[("internal_noop", "Internal no-op")], max_length=32),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("available", "Available"),
                            ("running", "Running"),
                            ("retry_wait", "Retry wait"),
                            ("cancellation_requested", "Cancellation requested"),
                            ("succeeded", "Succeeded"),
                            ("failed_terminal", "Failed terminal"),
                            ("cancelled", "Cancelled"),
                            ("quarantined", "Quarantined"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_category",
                    models.CharField(
                        choices=[("system", "System"), ("workspace", "Workspace")], max_length=16
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("payload_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "effect_class",
                    models.CharField(
                        choices=[
                            ("internal_idempotent", "Internal idempotent"),
                            ("external_ambiguous", "External ambiguous"),
                        ],
                        max_length=24,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("lease_owner", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("maximum_attempts", models.PositiveSmallIntegerField(default=3)),
                ("cancellation_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("succeeded", "Succeeded"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "failure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("transient", "Transient"),
                            ("permanent", "Permanent"),
                            ("ambiguous", "Ambiguous"),
                            ("lease_expired", "Lease expired"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "quarantine_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("restore", "Restore"),
                            ("ambiguous_outcome", "Ambiguous outcome"),
                            ("lease_loss", "Lease loss"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("available_at", "created_at", "id"),
            },
            managers=[
                ("execution_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "caller",
                    models.CharField(
                        choices=[("web", "Web"), ("operator", "Operator"), ("service", "Service")],
                        max_length=16,
                    ),
                ),
                ("caller_reference", models.CharField(max_length=64)),
                (
                    "operation",
                    models.CharField(choices=[("enqueue_job", "Enqueue job")], max_length=32),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed_terminal", "Failed terminal"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("result_classification", models.CharField(blank=True, default="", max_length=24)),
                ("failure_classification", models.CharField(blank=True, default="", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "resulting_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="jobs.job",
                    ),
                ),
            ],
            managers=[
                ("execution_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("worker_id", models.CharField(max_length=64)),
                ("lease_id", models.UUIDField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("retryable", "Retryable"),
                            ("terminal", "Terminal"),
                            ("cancelled", "Cancelled"),
                            ("ambiguous", "Ambiguous"),
                            ("lease_lost", "Lease lost"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "error_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("transient", "Transient"),
                            ("permanent", "Permanent"),
                            ("ambiguous", "Ambiguous"),
                            ("lease_expired", "Lease expired"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="jobs.job",
                    ),
                ),
            ],
            managers=[
                ("execution_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["state", "available_at", "created_at"], name="job_claim_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["state", "lease_expires_at"], name="job_lease_recovery_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["workspace", "state"], name="job_workspace_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "queued",
                            "available",
                            "running",
                            "retry_wait",
                            "cancellation_requested",
                            "succeeded",
                            "failed_terminal",
                            "cancelled",
                            "quarantined",
                        ),
                    )
                ),
                name="job_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("job_type__in", ("internal_noop",))), name="job_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_category__in", ("system", "workspace"))),
                name="job_target_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effect_class__in", ("internal_idempotent", "external_ambiguous"))
                ),
                name="job_effect_class_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result__in", ("", "succeeded", "cancelled", "failed", "quarantined"))
                ),
                name="job_result_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("failure__in", ("", "transient", "permanent", "ambiguous", "lease_expired"))
                ),
                name="job_failure_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quarantine_reason__in", ("", "restore", "ambiguous_outcome", "lease_loss"))
                ),
                name="job_quarantine_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_version", 1)), name="job_payload_version_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum_attempts__gte", 1)), name="job_max_attempts_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("maximum_attempts"))),
                name="job_attempt_count_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_id__isnull", False),
                        ("lease_owner__regex", "^[A-Za-z0-9._~-]{1,64}$"),
                        ("state__in", ("running", "cancellation_requested")),
                    ),
                    models.Q(
                        ("lease_expires_at__isnull", True),
                        ("lease_id__isnull", True),
                        ("lease_owner", ""),
                        (
                            "state__in",
                            (
                                "queued",
                                "available",
                                "retry_wait",
                                "succeeded",
                                "failed_terminal",
                                "cancelled",
                                "quarantined",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="job_lease_state_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["workspace", "operation", "created_at"], name="idempotency_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("workspace", "caller", "caller_reference", "operation", "idempotency_key"),
                name="unique_generic_idempotency_scope",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key__regex", "^[A-Za-z0-9._~-]{16,128}$")),
                name="generic_idempotency_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="generic_idempotency_fingerprint_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("caller_reference__regex", "^[A-Za-z0-9._~-]{1,64}$")),
                name="generic_idempotency_caller_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("caller__in", ("web", "operator", "service"))),
                name="generic_idempotency_caller_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation__in", ("enqueue_job",))),
                name="generic_idempotency_operation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("pending", "succeeded", "failed_terminal"))),
                name="generic_idempotency_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("result_classification__in", ("", "job_enqueued"))),
                name="generic_idempotency_result_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("failure_classification__in", ("", "invalid_request"))),
                name="generic_idempotency_failure_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failure_classification", ""),
                        ("result_classification", ""),
                        ("resulting_job__isnull", True),
                        ("state", "pending"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_classification", ""),
                        ("result_classification", "job_enqueued"),
                        ("resulting_job__isnull", False),
                        ("state", "succeeded"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_classification", "invalid_request"),
                        ("result_classification", ""),
                        ("resulting_job__isnull", True),
                        ("state", "failed_terminal"),
                    ),
                    _connector="OR",
                ),
                name="generic_idempotency_outcome_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="jobattempt",
            index=models.Index(fields=["job", "attempt_number"], name="job_attempt_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "attempt_number"), name="unique_job_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        (
                            "running",
                            "succeeded",
                            "retryable",
                            "terminal",
                            "cancelled",
                            "ambiguous",
                            "lease_lost",
                            "quarantined",
                        ),
                    )
                ),
                name="job_attempt_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("worker_id__regex", "^[A-Za-z0-9._~-]{1,64}$")),
                name="job_attempt_worker_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "error_category__in",
                        ("", "transient", "permanent", "ambiguous", "lease_expired"),
                    )
                ),
                name="job_attempt_error_valid",
            ),
        ),
    ]
