# Generated by Django 5.2.16 on 2026-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="job_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="job_target_category_valid",
        ),
        migrations.AddField(
            model_name="job",
            name="expected_revision_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="expected_scene_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="projection_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("internal_noop", "Internal no-op"),
                    ("rebuild_scene_search_projection", "Rebuild Scene search"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="target_category",
            field=models.CharField(
                choices=[("system", "System"), ("workspace", "Workspace"), ("scene", "Scene")],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("job_type__in", ("internal_noop", "rebuild_scene_search_projection"))
                ),
                name="job_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_category__in", ("system", "workspace", "scene"))),
                name="job_target_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_scene_version__isnull", True),
                    ("expected_scene_version__gte", 1),
                    _connector="OR",
                ),
                name="job_expected_scene_version_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expected_revision_id__isnull", True),
                        ("expected_scene_version__isnull", True),
                        ("job_type", "internal_noop"),
                        ("projection_version", ""),
                    ),
                    models.Q(
                        ("expected_revision_id__isnull", False),
                        ("expected_scene_version__isnull", False),
                        ("job_type", "rebuild_scene_search_projection"),
                        ("projection_version", "scene-search-v1:simple-v1"),
                        ("target_category", "scene"),
                        ("target_id__isnull", False),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="job_type_parameters_consistent",
            ),
        ),
    ]
