# Generated by Django 5.2.16 on 2026-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_job_job_type_valid_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="job_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="job_target_category_valid",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="job_type_parameters_consistent",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("internal_noop", "Internal no-op"),
                    ("rebuild_scene_search_projection", "Rebuild Scene search"),
                    ("validate_legacy_import", "Validate legacy import"),
                    ("generate_ai_scene_suggestion", "Generate AI Scene suggestion"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="target_category",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("workspace", "Workspace"),
                    ("scene", "Scene"),
                    ("import_batch", "Import batch"),
                    ("ai_request", "AI request"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "job_type__in",
                        (
                            "internal_noop",
                            "rebuild_scene_search_projection",
                            "validate_legacy_import",
                            "generate_ai_scene_suggestion",
                        ),
                    )
                ),
                name="job_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_category__in",
                        ("system", "workspace", "scene", "import_batch", "ai_request"),
                    )
                ),
                name="job_target_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expected_revision_id__isnull", True),
                        ("expected_scene_version__isnull", True),
                        ("job_type", "internal_noop"),
                        ("projection_version", ""),
                    ),
                    models.Q(
                        ("expected_revision_id__isnull", False),
                        ("expected_scene_version__isnull", False),
                        ("job_type", "rebuild_scene_search_projection"),
                        ("projection_version", "scene-search-v1:simple-v1"),
                        ("target_category", "scene"),
                        ("target_id__isnull", False),
                        ("workspace__isnull", False),
                    ),
                    models.Q(
                        ("expected_revision_id__isnull", True),
                        ("expected_scene_version__isnull", True),
                        ("job_type", "validate_legacy_import"),
                        ("projection_version", "story-engine-scenes-v1"),
                        ("target_category", "import_batch"),
                        ("target_id__isnull", False),
                        ("workspace__isnull", False),
                    ),
                    models.Q(
                        ("effect_class", "external_ambiguous"),
                        ("expected_revision_id__isnull", False),
                        ("expected_scene_version__isnull", False),
                        ("job_type", "generate_ai_scene_suggestion"),
                        ("projection_version", "ai-scene-v1"),
                        ("target_category", "ai_request"),
                        ("target_id__isnull", False),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="job_type_parameters_consistent",
            ),
        ),
    ]
